.gitignore, sdk/diffgram/file/file.py
Links to docs:
https://diffgram.readme.io/reference#file-copy-2
https://diffgram.readme.io/docs/files
=> Added file copy function

sdk/diffgram/core/core.py, sdk/diffgram/job/job.py
Still WIP
Refer to: https://github.com/diffgram/training_data/pull/161 for Main API changes
=> Attach Directories in Job Creation/Update

.circleci/config.yml, docker-compose.yaml, frontend/Dockerfile
Adding SAME_HOST env variable to docker compose. Context of this is that on old settings.py the default value was being used so it was working. Now with refactored version, we have to make sure to set the correct value on docker compose file
=> Fix problems with docker startup

default/play_and_scripts/scripts/create_database.py
Context of creating Database automatically in helm chart creation.
=> Adding missing script for helm setup

default/methods/attribute/attribute_template_group_update.py
Now add only condition of not None and always update the label file list if its an array even if array is empty.
=> Fix - File list was not updating if list was empty since empty list is Falsy.

frontend/build/webpack.base.conf.js, frontend/build/webpack.dev.conf.js, local_dispatcher/local_dispatch.py
Still need to test if they are working in multi host context.
=> Icons now loading in single host context.

.github/workflows/diffgram_testing.yaml
Context of video freezing on some test runs.
=> Cypress CPU Profiling

shared/alembic/versions_opencore/alembic_2021_05_12_10_11_990839b415fc_add_prelabeled_data_to_input_batch.py
Two alembic version had conflict so solving it here.
=> fix: fix alembic version ordering

README.md, install.py, requirements.txt
- Now we can test the DB connection before starting the docker files.
- Also added colors to the prints to for better reading.
- I'm also adding a requirements.txt for the install script, so now users will need to install dependencies before running installer. An exception will be raised indicating that they should run `pip install -r requirements.txt` before running the script if the don't have a dependency.
- For now the only dependency I added is sql aclhemy for connection tests.
=> Install Scripts Improvements

frontend/src/components/share/share_member_list.vue, shared/database/user.py
=> Add member's email to the member list in the project settings

walrus/methods/machine_learning/semantic_segmentation.py
This file was using specifically GCP upload functions, so it was not working with S3 or azure. Now it uses the wrapper to support S3 and Azure connections.
=> Use data tools in semantic segmentation

walrus/methods/video/video.py
Was still pending on a file so removing it here.
=> fix: remove fps conversion ratio concept

default/methods/model/model_run_list.py, default/methods/source_control/file/file_browser.py, default/routes_init.py, default/tests/methods/model/test_model_run_list.py, frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/model_runs/model_run_colors.js, frontend/src/components/model_runs/model_run_selector.vue, frontend/src/components/regular/button_with_menu.vue, frontend/src/components/source_control/dataset_explorer.vue, frontend/src/components/source_control/directory_list.vue, frontend/src/components/source_control/file_manager_sheet.vue, frontend/src/components/source_control/file_preview.vue, frontend/src/components/video/frame_preview.vue, frontend/src/components/video/video.vue, frontend/src/components/vue_canvas/drawable_canvas.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/components/vue_canvas/v_bg.vue, frontend/src/components/vue_canvas/video_drawable_canvas.vue, frontend/src/vue-canvas.js, frontend/yarn.lock, shared/annotation.py, shared/database/annotation/instance.py, shared/database/model/model_run.py, walrus/methods/input/process_media.py, walrus/methods/video/video.py
This is the V1 for the dataset explorer feature. Some things aimed to be released here are:
- Support for multiple datasets rendering in annotation core
- Support for multiple canvas renders
- Better support for Model Run Concepts
- Better data browsing with instances previews.
=> Dataset Explorer

default/tests/methods/model/test_model_run_list.py, frontend/src/components/input/instance_schema_mapper.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/source_control/dataset_explorer.vue
=> Show ground truth by default

frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_wizard_sheet.vue
Small fixes on ui wizard:
1. Progress bar got stucked if we deleted a file because the totat size was not being substracted on deletion.
2. Continue/Previous step buttons were not correctly repositioned if the windows was made smaller. It should now work fine with smaller heights
=> UI Wizard continue button positioning and progressbar bugfixes

frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/cypress/support/commands.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/ghost_canvas_available_alert.vue
based on prior frame move test case
=> add a WIP test case for ghost box

default/main.py, walrus/main.py, walrus/methods/input/upload.py
Context of really big annotation file (100+ MB). Flask defaults to return 413
=> Increase max upload size

frontend/src/components/input/new_or_update_upload_screen.vue
When uploading 100,000+ files to the media queue, it can be pretty slow to send the request one by one. But we also don't want to send 100,000 requests in parellel as both the client and server can get out of resource to perform those operations.
For now I've limited the request to got in batches of 40 just as an initial test to see how the system performs. But the key feature here is that now we have that control on the input creation throughput.
=> Allow max concurrent request for input update

default/methods/batch/append_to_batch.py, default/routes_init.py, frontend/package.json, frontend/src/components/annotation/toolbar.vue, frontend/src/components/input/input_view.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/input/upload_wizard_sheet.vue, frontend/yarn.lock, shared/alembic/versions_opencore/alembic_2021_07_05_10_06_13e0cabfe99b_add_temp_dir_path_to_batch.py, shared/annotation.py, shared/database/batch/batch.py, shared/database/source_control/file.py, shared/query_engine/sqlalchemy_query_exectutor.py
In the context of large uploads. Accepting huge payloads is not considered a good practice so implementing a chunking process to upload huge payloads on a batch to prevent server timeouts.
=> Chunk uploads into smaller sizes

default/methods/source_control/file/file_browser.py, frontend/src/components/source_control/dataset_explorer.vue
On the recent changes to the pagination, the page number key was changed. There were some pending places that needed the name change on the dataset explorer which was causing the pagination not to work properly
=> Dataset Explorer Page number key name

default/methods/query_engine/query_suggest.py, walrus/methods/input/input_update.py
Save retry as events instead of emailing super admins.
=> Remove email sending and permissions for query suggest

frontend/src/components/input/new_or_update_upload_screen.vue
Context of cloud import not showing the complete screen when the images/videos finish uploading.
=> Added flag to complete upload for videos

default/methods/project/project_list.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, shared/database/project.py, shared/database/source_control/working_dir.py, walrus/methods/input/process_media.py
Project images where not showing even though project had images. Now the cache is regenerating correctly.
=> Regenerate cache for project images on image upload

default/methods/source_control/file/file_update.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/source_control/file_manager_sheet.vue, frontend/src/components/video/frame_preview.vue, frontend/src/components/video/video.vue, frontend/yarn.lock, walrus/methods/input/process_media.py, walrus/methods/sync_events/sync_actions_handler.py
Task ID is not available on file context so we need to add the object exists verification
=> Verify task id exists in to avoid interpolation crash on non-task context

shared/database/user.py
After 10 months, profile picture URLs where expiring
=> Regenerate profile signed urls

README.md
Add cheatsheet link on quickstart section, and moved quickstart section a bit higher in the readme file.
=> Added cheatsheet link

frontend/src/components/annotation/media_core.vue, frontend/src/components/annotation/thumbnail.vue, frontend/src/components/sync_events/sync_events_list.vue, shared/utils/source_control/file/file_transfer_core.py, walrus/methods/sync_events/sync_actions_handler.py
Added an extra except clause where we create a new session to update the error status and delete the failed sync action.
Aso improved some styles on media core thumbnails while testing and debugging
=> Session Loop Fix

frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/src/components/connection/connection_form.vue, install.py, requirements.txt, walrus/methods/connectors/azure_connector.py, walrus/methods/connectors/connector_interface.py, walrus/methods/connectors/google_cloud_storage_connector.py, walrus/methods/connectors/s3_connector.py, walrus/tests/connectors/test_s3.py
Add better connection testing both on the install.py script as well as the connection testing on the UI.
This will add permissions testing for S3, GCP and Azure providers.
=> Connection Testing Improvements

default/methods/batch/append_to_batch.py, default/methods/batch/batch_detail.py, default/routes_init.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/cypress/support/commands.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/input/upload_wizard_sheet.vue, shared/alembic/versions_opencore/alembic_2021_07_21_13_27_7ff038954a96_add_download_status_on_batch.py, shared/database/batch/batch.py
This will help users know when validations are in progress and avoid confusion on UI getting stuck or something similar.
=> Improve Loading States File Wizard

default/main.py, frontend/src/components/input/upload_summary.vue, shared/data_tools_core_azure.py
Fixes batched upload failing when using azure backend
=> Fix batch splitted upload in azure

default/methods/source_control/file/file_exists.py, default/tests/methods/source_control/file/test_file_exists.py, frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/input_view.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_wizard_sheet.vue, shared/alembic/versions_opencore/alembic_2021_07_30_12_14_3e67f31e1a08_add_original_filename_index.py, shared/database/source_control/file.py, shared/tests/test_utils/data_mocking.py, walrus/methods/input/packet.py, walrus/tests/methods/input/test_packet.py
Add the ability to read JSON files and fetch the diffgram file using the original_filename.
=> Upload Wizard: support for updates via filename

frontend/src/components/annotation/annotation_core.vue
Project is not avaialable in props on task context.
=> Fix Task Cache regeneration

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/vue_canvas/instance_list.vue
Hotkey for show/hide instances
Opacity control
=> Polygon tool improvements

default/methods/report/report_runner.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/report/CSVReportFormatter.ts, frontend/src/components/report/charts/bar_chart.vue, frontend/src/components/report/report.vue, shared/alembic/versions_opencore/alembic_2021_08_11_14_26_ce2ecfac6416_add_group_by_labels.py, shared/database/report/report_template.py
Approach is to add a new flag/column to the report template called `group_by_labels`. This will change the query so that the groupby also groups by label_file_id.
=> Add Label Count Report Support

frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/src/components/input/DiffgramExportFileIngestor.ts, frontend/src/components/input/diffgram_export_validator.vue, frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/input/upload_wizard_sheet.vue, frontend/src/utils/colorUtils.js, shared/annotation.py, shared/database/export.py, shared/database/image.py, shared/database/text_file.py, shared/tests/test_utils/data_mocking.py, walrus/methods/export/export_generation.py, walrus/methods/export/export_web.py, walrus/methods/input/packet.py, walrus/methods/input/process_media.py, walrus/methods/video/video.py, walrus/tests/methods/export/test_export_generation.py
Add ability to import data from a Diffgram Export JSON using the upload wizard.
=> Ingest Data From Diffgram Export JSON

walrus/methods/video/interpolation.py
Small bug was preventing users to use interpolation on task context.
=> Interpolation Bugfix

default/tests/shared/test_annotation.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_data_integrity.js, frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_core_command_manager.js, frontend/src/components/context_menu/context_menu.vue, frontend/yarn.lock, shared/annotation.py, walrus/methods/input/packet.py
Use Same Frame value and remove soft_delete on hash collisions
=> Use Same Frame value and remove soft_delete on hash collisions

default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/annotation_core.vue
Add a frame buffer fetch in parallel
=> Fetch Frame Buffers In Parallel

walrus/methods/input/input_update.py
Remove related tasks when archiving / retrying input
=> Remove related tasks when archiving / retrying input

frontend/src/components/annotation/annotation_core.vue
Add figure id to polygon when adding midpoint
=> Add figure id to polygon when adding midpoint

default/methods/report/report_runner.py, shared/alembic/versions_opencore/alembic_2021_09_16_11_27_c1e5966dc826_add_index_for_instance_table.py
Adding some indexes to key columns that remove sequential scans on certain reports.
=> Improve Performance of Report Queries

shared/data_tools_core.py, shared/data_tools_core_azure.py, shared/data_tools_core_gcp.py, shared/data_tools_core_s3.py
Added this link: https://diffgram.readme.io/docs/data_tools
And improved comments on all the data_tools classes.
=> improved comments and documentation for data_tools classes

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/commands/create_instance_command.js, frontend/src/components/annotation/commands/update_instance_command.js, frontend/src/components/annotation/toolbar.vue, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseUp.ts, shared/annotation.py
just putting here as starting point
=> Add rotation keypoints - Placeholder

default/methods/source_control/file/file_exists.py, shared/permissions/project_permissions.py, shared/regular/regular_member.py
Fixes various errors when accessing public project
=> Fix public project permissions

frontend/cypress/support/commands.js, walrus/methods/input/process_media.py, walrus/methods/video/video.py, walrus/requirements.txt
To improve a bit video write performance
=> Memory Guards, Queue Pressure Guard, Use cpu count to determine threads

shared/database/input.py, shared/database/video/sequence.py, walrus/methods/input/input_view.py, walrus/methods/input/process_media.py
This was due to some sequence failing to regenerate image preview.
Since this is not a crucial operation, I'm not raising an exception and just logging the error for further analysis.
=> Update Labels Fix Stale Inputs

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Fixes misplacement of keypoints when dragging entire instance
=> Drag keypoints fix

walrus/methods/video/video.py
Adding traceback to logs since some videos seem to fail from time to time.
=> Get visibility on movie py errors

frontend/cypress/integration/diffgram/annotate_files/03_instance_template_annotation_spec.js, frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/source_control/file_manager_sheet.vue, frontend/src/components/ui_schema/ui_schema_task_mock.js, frontend/yarn.lock
Stops using DB files or tasks and uses a mock to populate the canvas for the UI schema creation.
=> Mock Task For UI Schema Creation

default/methods/report/report_runner.py, frontend/src/components/report/report.vue
Now we can group by status. This will be useful for reports needed in other contexts like : https://github.com/diffgram/diffgram/issues/403
=> Add status to task report

default/methods/task/task_template/job_new_or_update.py, default/tests/methods/task/task_template/test_job_new_or_update.py, frontend/cypress/integration/diffgram/qa_slideshow/qa_slideshow_spec.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/qa_carousel.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/project/project_members_step.vue, frontend/src/components/project/project_new_wizard.vue, frontend/src/components/regular/wizard_navigation.vue, frontend/src/components/task/job/job_file_routing.vue, frontend/src/components/task/job/job_list.vue, frontend/src/components/task/job/job_pipeline_mxgraph.vue, frontend/src/components/task/job/task_template_wizard_creation/step_attach_directories_task_template.vue, frontend/src/components/task/job/task_template_wizard_creation/step_label_selection_task_template.vue, frontend/src/components/task/job/task_template_wizard_creation/step_name_task_template.vue, frontend/src/components/task/job/task_template_wizard_creation/step_ui_schema_task_template.vue, frontend/src/components/ui_schema/edit_overview_page.vue, frontend/src/components/vue_canvas/CanvasMouseTools.ts, frontend/tests/unit/task/job/task_template_wizard_creation/step_label_selection_task_template.spec.js
(Video explanation shared on slack channel)
Added docs here too https://diffgram.readme.io/docs/annotation-show-qa
=> Video on QA feature, new smooth zoom out, improve snap to feature

default/methods/task/task/task_by_id.py, default/methods/task/task/task_list.py, default/methods/task/task_template/job_mock_data.py, frontend/cypress/integration/diffgram/task_template/tasks_detail_pagination_spec.js, frontend/cypress/support/commands.js, frontend/src/components/annotation/labels_view.vue, frontend/src/components/project/project_manager.vue, frontend/src/components/regular/regular_table.vue, frontend/src/components/regular_concrete/task_status_icons.vue, frontend/src/components/task/job/job_list.vue, frontend/src/components/task/task/task_list.vue, frontend/src/components/upload_large.vue, shared/database/source_control/working_dir.py, shared/database/task/task.py, walrus/main.py, walrus/methods/data_mocking/generate_data.py
Adds basic pagination
fixes some other related things noticed during work
=> Paginate tasks

frontend/cypress/integration/diffgram/annotate_files/annotate_files_instance_drawing_spec.js, frontend/cypress/integration/diffgram/annotate_files/autoborder_spec.js, frontend/cypress/integration/diffgram/annotate_files/file_information_spec.js, frontend/cypress/support/commands.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/context_menu/polygon_borders_context_menu.vue, frontend/src/components/user/login.vue
1) Actual bug was super tiny, single condition here https://github.com/diffgram/diffgram/pull/420/commits/00e61306d95fdac31eaf24dc8bdfb3ea5d2d28ab
2) Most of this effort is on adding the e2e test for autoborder and associated refactors
[test](https://github.com/diffgram/diffgram/pull/420/files#diff-56d541fcb1946fd116c98e756503ab8386323987d743685a4e7e4a39fb331fcd)
[refactor](https://github.com/diffgram/diffgram/pull/420/files#diff-c4906e16d3e24724e4cddf79cf7a4e37100d6d04aa6dcc3251374fcb89b2211cR293)
The new test may still need some little details otherwise this is a small one to merge
=> Fix autoborder

frontend/cypress/integration/diffgram/user/user_login_spec.js, frontend/src/components/main_menu/menu.vue, frontend/src/components/project/project_new.vue, frontend/src/services/projectServices.js, frontend/src/store.js, frontend/tests/unit/main_menu/menu.spec.js
This will be a small PR:
-  remove useless DB icon from menu
- add drop down to the menu
- tests
=> Small improvements to the main toolbar

frontend/src/components/annotation/toolbar.vue, frontend/src/components/task/job/job_detail.vue, frontend/src/store.js
Context that we want a local copy for being able to edit the name
but we aren't getting the job data from this component
Not saying this is ideal but should work for now
=> Handle a case with resetting the name

default/methods/task/stats/fast_stats.py, default/routes_init.py, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/diffgram/admin_mock_data.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/stats/stats_panel.vue, frontend/src/components/vue_canvas/ghost_instance_list.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/router/router.js, frontend/src/services/mockServices.js, shared/database/task/task.py, walrus/methods/data_mocking/generate_data.py
=> Mock data and clean

shared/alembic/versions_opencore/alembic_2021_12_09_12_19_7505d378b3ae_add_eventhub.py, shared/database/event/eventhub.py, shared/database/system_events/system_events.py, shared/regular/regular_methods.py, shared/settings/settings.py, walrus/main.py, walrus/methods/eventhub/eventhub_new.py, walrus/methods/startup/system_startup_checker.py
Will check for any improvements that can prevent deadlocks from happening.
=> Re Enable Eventhub

frontend/cypress/integration/diffgram/qa_slideshow/qa_slideshow_spec.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/task_status.vue, frontend/src/components/annotation/toolbar.vue, frontend/tests/unit/annotation/task_status.spec.js, frontend/tests/unit/annotation/toolbar.spec.js
PR contains:
- displaying task status on the annotation UI
=> Add task status component

frontend/src/components/video/sequence_list.vue
drastically removes amount of render items and improves overall UI performance
=> fix: hide sequence list while playing

shared/alembic/versions_opencore/alembic_2021_12_14_14_57_efd1cf42073a_add_indexes_parent_file_id.py
Optimizes some queries related to 3D interface
=> Add indexes to file table parent_id

frontend/src/components/annotation/actions/is_complete.vue, frontend/src/components/annotation/task_status.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/dialogs/review_dialog.vue, frontend/tests/unit/dialogs/review_dialog.spec.js, shared/database/task/task.py, shared/database/task/task_event.py, walrus/methods/input/upload.py
- Fix closing dialog
- Add reviewer's comment on the task status menu
=> Fix details pointed by Anthony

default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/media_core.vue
Added filter by text file and sensor fusion files.
=> Add New Type to FIle Filter List

default/methods/user/account/account_verify.py, default/tests/shared/test_annotation.py, frontend/cypress/integration/diffgram/annotate_files/04_annotate_files_attributes_spec.js, frontend/cypress/integration/diffgram/annotate_files/08_annotate_files_video_annotation_tools_spec.js, frontend/cypress/integration/diffgram/annotate_files/09_annotate_files_data_integrity.js, frontend/src/components/3d_annotation/context_menu_3d_editor.vue, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/commands/create_instance_command.js, frontend/src/components/annotation/media_core.vue, frontend/src/components/annotation/utils/AnnotationSavePrechecks.ts, frontend/src/components/annotation/utils/SequenceUpdateHelpers.ts, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/context_menu/polygon_borders_context_menu.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/task/task/task_list.vue, frontend/src/components/video/sequence_list.vue, frontend/src/components/video/video.vue, frontend/src/components/vue_canvas/cuboid.js, frontend/src/components/vue_canvas/ghost_instance_list.vue, frontend/src/components/vue_canvas/video_drawable_canvas.vue, frontend/src/vue-canvas.js, frontend/tests/unit/annotation/annotation_core.spec.js, frontend/tests/unit/annotation/commands/commands.spec.js, frontend/tests/unit/annotation/utils/SequenceUpdateHelpers.spec.ts, shared/annotation.py
Improvements to prevent frames from not getting saved and wrong frame to be updated with new IDs when saving data.
=> Fix Concurrent Saving Frames Issues

shared/database/export.py, shared/database/task/task.py
When Session object is not provided, the serializer was crashing.
=> Fix Task List Serializer

default/methods/task/task_template/job_cancel.py, frontend/src/components/regular/button_with_confirm.vue, frontend/src/components/task/credential/credential_list.vue, frontend/src/components/task/job/job_cancel.vue, frontend/src/components/task/job/job_cancel_actions_button_container.vue, frontend/src/components/task/job/job_detail.vue
Remove the option to hard delete and only allow archiving task templates.
=> Remove hard delete and improve layouts

frontend/src/components/annotation/annotation_core.vue
1. Fixed instance template drawing on canvas, a function was accidentally deleted causing an exception.
2. Fixed the issue of task https://diffgram.com/task/87106 not loading. Issue was due to UI Schema missing some guard conditions when it was undefined.
=> Fix Instance Template Creation & Task Loading

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/video/video.vue
Temp workaround while performance improvements are made to blob store
=> Reduce Buffer Size

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/vue_canvas/instances/InstanceContext.ts, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Fixes: https://github.com/diffgram/diffgram/issues/563
=> DAD-46  only hover 1 instance when multiple instances overlayed

frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Fixes: https://github.com/diffgram/diffgram/issues/559
=> DAD-42 Do not allow select instances while drawing

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, frontend/src/components/vue_canvas/interactions/Interaction.ts, frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseDown.ts, frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseUp.ts
- Added occlude all children
- Added occlude children in direction
=> DAD-48 Occlude Childs

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue
Now we pan using the shift key on image/video UI
=> fix: change panning to shift key

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/vue_canvas/current_instance_template.vue, frontend/src/utils/instance_utils.js
Issue was that instance was not being initialized. Now this is fixed and also initialize_instance function was refactored and removed from annotation core to user the instance_uitils.js instead
=> fix: creating template on UI

.github/workflows/diffgram_testing.yaml, frontend/src/components/annotation/node_name_editor_keypoint_instance.vue, frontend/src/components/instance_templates/instance_template_creation_dialog.vue, frontend/src/components/vue_canvas/drawable_canvas.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, frontend/src/components/vue_canvas/interactions/AnnotationCoreInteractionGenerator.ts, frontend/src/components/vue_canvas/interactions/InstanceTemplateCreationInteractionGenerator.ts, frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseMove.ts, frontend/src/components/vue_canvas/interactions/interaction_types/keypoints/KeypointInstanceMouseUp.ts
Fixes:
- Double click on context menu was deleting instance
- Better select mechanisms on edit mode
- Hide target reticle on edit mode
- Add default node names to nodes (1,2,3...etc)
Also fixes all items in: https://github.com/diffgram/diffgram/issues/575
=> Instance Template Creation Fixes

default/methods/share/share.py, frontend/src/components/user/home/dashboard.vue
1) add super admin override
https://github.com/diffgram/diffgram/commit/622c140e4ffd75e5197aad4dccf1b0f4e7c4158e
2) Revert: Add back change project button
https://github.com/diffgram/diffgram/commit/18f376a41ec386c537ad845ba25ca3be4d69c7d1
=> Diffgram.com demo more users

default/methods/configs/is_open_source.py, default/methods/share/share.py, default/methods/startup/system_startup_checker.py, default/methods/user/account/account_new.py, default/methods/user/account/auth_code.py, default/routes_init.py, frontend/src/components/exam/exam_child_list.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/main_menu/menu_marketing.vue, frontend/src/components/marketing/home_unbounce.vue, frontend/src/components/regular/ahref_seo_optimal.vue, frontend/src/components/user/account/user_data_platform_new.vue, frontend/src/components/user/builder/builder_signup.vue, frontend/src/components/user/home/annotator_dashboard.vue, frontend/src/components/user/home/dashboard.vue, frontend/src/components/user/login.vue, frontend/src/services/configService.js, frontend/src/services/projectServices.js, shared/system_startup/system_startup_base.py, walrus/methods/startup/system_startup_checker.py
Fixes all items of https://github.com/diffgram/diffgram/issues/654
=> Improve Invite Experience & Bug Fixes

.github/workflows/diffgram_testing.yaml, default/methods/report/custom_reports/TaskReportRejectRatioReport.py, default/methods/report/report_runner.py, default/tests/shared/database/task/test_task_event.py, frontend/src/components/report/approval_reject_ratio.vue, frontend/src/components/report/charts/bar_stacked_horizontal_chart.vue, frontend/src/components/report/stats_task.vue, shared/alembic/versions_opencore/alembic_2022_02_22_10_32_0e90db072b0b_add_reviewer_and_assignee_to_task_events.py, shared/database/task/task.py, shared/database/task/task_event.py, shared/utils/task/task_complete.py, shared/utils/task/task_update_manager.py
Adds a report to the task template insights with the approval rejection ratio of the users
=> Approve/Reject Ratio Report

default/methods/account/transact/transaction_list.py, default/methods/action/action.py, default/methods/source_control/file/file_browser.py, default/methods/stats/stats.py, default/methods/task/credential/credential_list.py, default/methods/task/task_template/job_list.py, default/methods/task/task_template/job_new_or_update.py, default/methods/task/task_template/task_template_apply.py, default/tests/shared/database/task/job/test_job.py, frontend/src/components/vue_canvas/current_instance.vue, shared/annotation.py, shared/database/annotation/instance_template.py, shared/database/attribute/attribute_template_group.py, shared/database/event/event.py, shared/database/source_control/file.py, shared/database/task/job/job.py, shared/utils/task/task_complete.py
Grow ellipse from center when doing the initial drawn.
=> Create Ellipse From Center

default/methods/account/transact/transaction_list.py, default/methods/action/action.py, default/methods/source_control/file/file_browser.py, default/methods/stats/stats.py, default/methods/task/credential/credential_list.py, default/methods/task/task_template/job_list.py, default/methods/task/task_template/job_new_or_update.py, default/methods/task/task_template/task_template_apply.py, default/tests/shared/database/task/job/test_job.py, shared/annotation.py, shared/database/annotation/instance_template.py, shared/database/attribute/attribute_template_group.py, shared/database/event/event.py, shared/database/source_control/file.py, shared/database/task/job/job.py, shared/utils/task/task_complete.py
We need to update the job status on each task completion to guarantee that when new tasks are added, the job status is updated correctly.
=> Update job status on reviews and approvals

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/vue_canvas/CanvasMouseTools.ts, frontend/tests/unit/annotation/annotation_core.spec.js
Change padding to z key, turbo mode is still activated with shift key. Added unit tests to catch issues on any of those functionalities.
=> Change panning to z key and reactivate turbo mode

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/instance_type_multiple_select.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, frontend/src/services/instanceTemplateService.js
We can now customize the schema to show hide instance template from the project.
=> Show/Hide Instance Templates on UI Schema

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/context_menu/context_menu.vue
- Allow to focus instance with right click context menu
- Allot to focus instance with holding F+clicking instance
=> RIght Click Focus Instance

default/methods/share/share.py, shared/database/annotation/instance.py, shared/feature_flags/feature_checker.py, walrus/methods/export/export_web.py
[Improve/Fix: Where the plan comes from](https://github.com/diffgram/diffgram/commit/af7452f7126d8b23ffb2254476da799efe207646)
[Improve: Move super admin bypass to generic spot](https://github.com/diffgram/diffgram/commit/07996ae40a88b1de8ec2aba66a0011d2c5015468)
@PJEstrada Please check and what do you think?
*Edit. The failing tests seem kind of odd not sure how it would be related to these changes. Maybe the test runner is interacting oddly with the plan thing somehow?
=> Improve feature checker

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Now scale control points have better scales and a bit more "invisible drag space"
=> DAD-132 Adjust Rescale Control Points for Instance Templates

default/methods/ui_schema/ui_schema.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/ui_schema/edit_overview_page.vue, frontend/src/components/ui_schema/ui_schema_context_menu.vue, frontend/src/components/ui_schema/ui_schema_selector.vue, frontend/src/store.js
Now all the configs selected on the UI schema editor will be saved as default configs on startup when launching a task that has that UI Schema attached to it.
=> DAD-131 Save Configs at the UI Schema Level

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Now we can pan using the mouse wheel button.
=> DAD-145 Support pan with mouse wheel

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/annotation/qa_carousel.vue, frontend/src/components/video/video.vue
Better hotkeys support for navigating instances on both images and video.
- Now you can pause/play the slideshow.
- When paused you can navigate back and forward with arrows
- Activate / Deactivate slideshow with shift+R
=> Add Better Carrousel Navigation

default/methods/share/share.py
Tiny fix https://github.com/diffgram/diffgram/issues/748
[Fix: 500 if no limits](https://github.com/diffgram/diffgram/commit/272c98f8c9710e05cacb7e3c1059ec8344d1c179)
=> Fix: 500 if no limits

README.md, shared/database/event/event.py, shared/feature_flags/feature_checker.py
- feature_checker project would be undefined there
- event, mirror timeout we have on other context
- fix broken url on readme
doing this small things in seperate a pull request for sake of organization and so it can be reviewed
=> 3 Tiny fixes

default/methods/attribute/attribute.py, default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_wizard.vue, frontend/src/components/source_control/query_suggestion_menu.vue, frontend/src/helpers/tree_view/construct_tree.ts, shared/project_migration/ExternalMigrationManager.py, shared/query_engine/grammar.py, shared/query_engine/sqlalchemy_query_exectutor.py, walrus/methods/connectors/labelbox_connector.py
- Adds support for labels with & character
- Fixes small warning error
=> Dataset Explorer Fixes

.github/workflows/diffgram_testing.yaml, .github/workflows/e2e_tests.yaml, .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml, frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js, walrus/methods/data_mocking/generate_data.py
- Allows for users in organization `['OWNER', 'COLLABORATOR', 'MEMBER']` to user the `/deploy` command to deploy the pr to staging environment.
- The Action will deploy the current branch and show the URL in a comment on the PR thread.
=> Add deploy/test by comment

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/input/upload_wizard_sheet.vue, frontend/src/components/vue_canvas/v_bg.vue
Removed dark bg when changing frames on video.
=> Remove blipping when changing video frame

default/methods/user/account/account_verify.py, shared/communicate/email.py
=> Fancy email verify

default/methods/task/task_template/job_new_or_update.py, frontend/src/components/dialogs/add_assignee.vue, frontend/src/components/task/task/task_list.vue, shared/database/task/job/job.py
Now users should be displayed correctly on job details.
=> Fix User Assignment on Job Detail

frontend/src/components/attribute/attribute_group_list.vue
Fixes regression on global attr display
=> Fix Global Attribute Display

walrus/methods/connectors/s3_connector.py
=> fix: s3 export bug

default/methods/annotation/labels/view.py, shared/database/project.py
Adds schema concept to the label dict endpoint
=> DAD-276 Fix Label Dict Endpoint to Include Schema Concept

frontend/src/components/project/project_migration_progress_step.vue, frontend/src/components/project/project_migrations_error_dialog.vue, frontend/src/components/project/project_migrations_list.vue, frontend/src/components/regular/info_multiple.vue, shared/database/project_migration/project_migration.py, shared/model/model_manager.py, walrus/methods/connectors/labelbox_connector.py
[Improve defensive aspects, schema context, and logging](https://github.com/diffgram/diffgram/commit/39844e16a0c4429c17dc2f33ece2258db3c6f452)
[Add access to view dataset and general log](https://github.com/diffgram/diffgram/commit/a132cb37a821a5ed66325a15c8650038b0f24377) 
[update for schema context](https://github.com/diffgram/diffgram/commit/740ec97738030c9293fa96c765ceaccc0be1fae8)
=> Migration more updates

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/audio_annotation/render_elements/waveform_selector.vue, shared/database/source_control/file.py
=> Minor bug fixes

default/methods/attribute/attribute_template_group.py, frontend/src/components/annotation/annotation_core.vue, shared/database/attribute/attribute_template_group.py
=> Fix global attributes on the Image interface

default/main.py, default/requirements.txt, eventhandlers/action_runners/ActionRunner.py, eventhandlers/action_runners/AzureTextAnalyticsSentiment.py, eventhandlers/action_runners/DeepCheckImagePropertyOutliers.py, eventhandlers/action_runners/ExportActionRunner.py, eventhandlers/action_runners/GoogleVertexAIObjectDetectionPrediction.py, eventhandlers/action_runners/SampleActionBoilerplate.py, eventhandlers/action_runners/TaskTemplateActionRunner.py, eventhandlers/action_runners/base/ActionCompleteCondition.py, eventhandlers/action_runners/base/ActionCondition.py, eventhandlers/action_runners/base/ActionRunner.py, eventhandlers/action_runners/base/ActionTrigger.py, eventhandlers/action_runners/huggingface_zeroshot.py, eventhandlers/action_runners/runners_mapping.py, eventhandlers/main.py, eventhandlers/requirements.txt, frontend/src/components/action/action_config_factory.vue, frontend/src/components/action/action_configurations/deepchecks/img_properties_outliers/img_properties_outliers_action_config.vue, frontend/src/components/action/action_configurations/deepchecks/img_properties_outliers/img_properties_outliers_action_details.vue, shared/database/action/action_run.py, shared/database/source_control/working_dir.py, shared/database_setup_supporting.py, walrus/main.py
=> Deep Checks Action

frontend/src/components/input/new_or_update_upload_screen.vue, walrus/methods/connectors/s3_connector.py, walrus/methods/input/process_media.py
-> Makes downloading tiffs from CSV file work
-> Fixes 2 small None items were noise in debugging
=> Tiff fixes

shared/export/export_generation.py
Fix Add Keypoints data to Export
=> Fix Add Keypoints data to Export

default/methods/startup/system_startup_checker.py, shared/connection/connection_operations.py
-> Self test to ensure basics work at startup config, prevent user having to manually test
-> Remove try block to help surface error eariler
-> Add more guards and returns within encrypt_secret()
=> Add self_test

default/methods/labels/label_schema_list.py
adds: allow_if_project_is_public
=> Allow Fetch Schema on Public Projects

default/methods/attribute/attribute_template_list.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/instance_detail_list_view.vue
Saving was not working properly due to wrong indexing during update of attributes.
=> Fix Global Attributes Saving

default/methods/auth/oidc/oidc_auth_callback.py, default/methods/configs/oidc_is_set.py, default/methods/startup/system_startup_checker.py, default/methods/user/logout.py, eventhandlers/startup/system_startup_checker.py, shared/auth/KeycloakDiffgramClient.py, shared/auth/OIDCProvider.py, shared/helpers/permissions.py, shared/permissions/KeycloakPolicyEnforcer.py, shared/settings/settings.py, walrus/methods/startup/system_startup_checker.py
Add a new `OIDCProvider` Class to serve as an OIDC client factory. The idea is to be able to support different OIDC providers in the future across a standard interfaces and leave client-specific implementation details to the client specific libraries.
=> Improvements to OIDC Abstraction Layer

default/methods/attribute/attribute.py
Fixes issue in the context of an SDK user.
=> Fix Attribute API Options Creation

default/methods/attribute/attribute.py, default/methods/attribute/attribute_template_group_update.py
For now removing as we get more overall usage data from all users.
=> fix: remove rate limiting on attribute endpoints

shared/settings/settings.py
Fixing url generation pattern and add install info
=> Fix Cognito Settings

eventhandlers/action_runners/actions/HuggingFaceZeroShot.py, frontend/src/components/text_annotation/text_annotation_core.vue, shared/annotation.py
Fix multi select for global attributes on the text interface and modify HuggingFace Zero Shot action to apply it correctly
=> Fix multi select

walrus/requirements.txt
https://github.com/lengstrom/fast-style-transfer/issues/253#issuecomment-777344545
=> Fix Video Upload

default/methods/task/task_template/job_list.py, frontend/src/components/tag/tag_select.vue, frontend/src/components/task/job/job_list.vue
-> Small improvements
-> Make job_list work in SDK context
Mainly https://github.com/diffgram/diffgram/commit/74189fdb7a9ca0fb0594c900891f94b0a097c27d
=> Tag small improvements

CONTRIBUTING.md, README.md
Hello.
I noticed that the link to the guidelines is broken.
This PR is to correct the link.
---
Thank you for your awesome work :)
=> fix contribute guide line link

default/methods/action/action_run_list.py, default/routes_init.py, default/tests/shared/database/task/test_task_event.py, eventhandlers/action_runners/ActionRegistrar.py, eventhandlers/action_runners/actions/Webhook.py, eventhandlers/action_runners/actions/__init__.py, eventhandlers/action_runners/base/ActionRunner.py, frontend/src/components/action/action_configurations/Webhook/Webhook.vue, frontend/src/components/action/component_mapping.js, frontend/src/services/actionService.js, shared/alembic/versions_opencore/alembic_2022_07_28_11_40_73fd663f4914_add_action_run_indexes.py, shared/database/action/action.py, shared/database/action/action_run.py, shared/database/task/task_event.py, shared/utils/sync_events_manager.py
Adds support for webhooks using the workflow system and adds multiple new events as allowed events for actions triggers.
=> Webhook Action Support 

frontend/src/components/task/job/job_list.vue, frontend/src/store.js
[bugfix](https://github.com/diffgram/diffgram/commit/3ebbce5f23b790c4cb91d8d44df478661c5d2547)
[Prevent confusing state](https://github.com/diffgram/diffgram/commit/c2b33ac4dde25b2dbd03c7c787dd3d1bdec804cb)
=> Fix project string

shared/connection/s3_connector.py, shared/url_generation.py
Allows thumbnails upload with custom signed urls
=> Thumbnail Uploads With Custom Signer

default/methods/task/task/task_update.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/report/report.vue, frontend/src/components/report/report_dashboard.vue, shared/utils/task/task_update_manager.py
* Adds button to set task as incompleted.
* Fixes small error on reports loading
=> Mark task as incomplete

frontend/src/components/attribute/attribute_group.vue
Add chips to the tree attribute, that annotator can see what items are applied
=> Display selected items

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/store.js
Annotation tool now stores the latest selected tool in vuex to keep it across files changes or task changes.
=> feat: add last selected tool to vuex

frontend/src/components/label/label_schema_selector.vue, frontend/src/components/label/label_select_only.vue, frontend/src/components/source_control/dataset_explorer.vue
- Add schema selector
- Default selected schema to the default
- Select label based on selected schema
=> Add schema selector

frontend/src/components/source_control/dataset_explorer.vue
- improve UI of the dataset explorer
- fix UI bugs on the dataset explorer
=> Explorer UI improvements

frontend/src/components/source_control/dataset_explorer.vue
=> Improve explorer

default/methods/project/regen_file_stats.py, default/routes_init.py, frontend/src/components/project/settings.vue
Add files stats regeneration button for project.
=> feat: add files regeneration button

.github/workflows/kubernetes_diffgram_enterprise_deploy.yaml, shared/queueclient/QueueClient.py, shared/settings/settings.py
feat: add SSL config to rabbit mq
=> feat: add SSL config to rabbit mq

default/methods/project/regen_file_stats.py, default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/media_core.vue, frontend/src/components/source_control/dataset_explorer.vue, shared/alembic/versions_opencore/alembic_2022_09_12_18_15_56192ed7c6cd_new_file_indexes.py, shared/database/source_control/file.py, shared/database/source_control/file_stats.py
Fixes file stats regen script.
Adds indexes for better performance
Adds parallel url regeneration on UI
=> fix: regen script and url regen on dataset explorer

shared/alembic/versions_opencore/alembic_2022_09_14_07_10_072c6491c0b5_new_file_stats_indexes.py, shared/permissions/api_permissions.py
better logs permissions and indexes
=> Permissions & Indexes Files Stats

default/methods/source_control/file/file_get_signed_url.py, frontend/src/components/source_control/directory_selector.vue, shared/auth/CognitoDiffgramClient.py
=> Fix Dataset Filter

default/methods/source_control/file/file_browser.py, default/methods/task/task_template/task_template_add_files.py, eventhandlers/ConsumersCreator.py, eventhandlers/JobsConsumer.py, frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/media_core.vue, frontend/src/components/regular/button_with_menu.vue, frontend/src/components/source_control/dataset_explorer.vue, frontend/src/components/source_control/dataset_explorer_toolbar.vue, frontend/src/components/source_control/file_preview.vue, frontend/src/services/taskTemplateService.js, frontend/yarn.lock, shared/auth/CognitoDiffgramClient.py, shared/database/source_control/file.py, shared/database/task/task.py, shared/permissions/job_permissions.py, shared/queueclient/QueueClient.py, shared/utils/task/task_update_manager.py
Adds the ability to create tasks from query selection.
=> Add Query Results as Tasks

default/methods/configs/mailgun_is_set.py, shared/connection/azure_connector.py, shared/connection/s3_connector.py, shared/data_tools_core_azure.py, shared/regular/regular_input.py, shared/settings/settings.py, shared/url_generation.py, walrus/methods/input/packet.py
Adds support for uploading by reference from azure
=> CORE-3 Azure Pass By Reference

shared/helpers/permissions.py
Replace Access Token With ID Token Cognito
=> Replace Access Token With ID Token Cognito

shared/helpers/permissions.py
Compresses both refresh and ID token during refresh process.
=> Compress Token During Token Refresh

shared/data_tools_core_s3.py, walrus/methods/input/upload.py
Parts where not properly being added to the input object, so final chunking was missing parts during uploads bigger than minimal chunk size.
=> Fix MinIO Chunking Process

.github/workflows/e2e_tests.yaml, .github/workflows/kubernetes_diffgram_enterprise_deploy.yaml, .github/workflows/publish_docker_images.yaml, docker-compose.yaml
Migrated actions to dockerhub and published old images into new registry.
=> Dockerhub Image registry change

shared/database/image.py, shared/database/source_control/file.py, shared/url_generation.py
Includes now bucket name and connection ID
=> Fixes for file fetch with signed url

default/methods/task/task_template/job_info_builder.py, frontend/src/components/ui_schema/ui_schema.ts, frontend/src/components/ui_schema/ui_schema_context_menu.vue, frontend/src/helpers/interfaces/genaral/SchemaUI.ts, frontend/src/services/schemaUIService.ts, shared/database/task/job/job.py
Fix creation of the new UI schema
=> Fix us shema request

shared/connection/azure_connector.py, shared/connection/google_cloud_storage_connector.py, shared/connection/s3_connector.py, shared/ingest/allowed_ingest_extensions.py, walrus/methods/input/process_media.py
* Centralizes supported file types
* FIxes bug on GCP imports with uppercase extensions
=> Fix: Uppercase Imports on GCP

shared/export/export_generation.py
Adds export support for compound files:
* Compound files will have the child files nested inside the file ID key.
=> CORE-23 Export Support for Compound Files

frontend/src/components/regular/file_preview_with_hover_expansion.vue
Quick fix: Props where missing colon to be used as numbers.
=> fix: extra white space on task preview

default/methods/source_control/file/remove.py, frontend/src/components/annotation/media_core.vue, frontend/src/components/regular/file_preview_with_hover_expansion.vue, frontend/src/components/source_control/compound_file_preview.vue, frontend/src/components/source_control/dataset_explorer.vue, frontend/src/components/source_control/file_preview.vue, frontend/src/components/source_control/file_preview_details_card.vue, frontend/src/components/task/task/task_list.vue, shared/utils/job_dir_sync_utils.py
* Adds support for compound files on tasks list.
* Adds file detail preview to show file type and name on all file types
* Fixes bug on compound file delete not deleting child files
* Adds task preview for compound files
=> CORE-24 Compound File Support on Tasks List

pull_request_template.md
This adds the new PR template for  developers to user when submitting code to Diffgram.
I have...
https://diffgram.readme.io/docs/developer-contribution-guide
I have...
=> feat: CORE-27 New PR Template

frontend/.storybook/manager-head.html, frontend/tests/unit/annotation/actions/is_complete.spec.js, frontend/tests/unit/annotation/toolbar.spec.js
=> Refactor directory selector

default/methods/task/task/task_list.py, frontend/src/components/task/task/task_list.vue, shared/database/task/task.py
Improves fetch task list speed for cases where list case files with connection IDs.
I have...
I have...
=> fix: improve speed of task list fetching for files with connection ids

.github/workflows/update_readme.yaml, default/docs/new_discussion.yml, default/docs/swagger_spec.json, default/main.py, default/methods/discussions/discussion_comment_new.py, default/requirements.txt, default/swagger_setup.py, pull_request_template.md, walrus/docs/export_list.yml, walrus/docs/swagger_spec.json, walrus/main.py, walrus/methods/export/export_view.py, walrus/requirements.txt, walrus/swagger_setup.py
This PR shows an example of how we can generate swagger docs and sync the definitions with OpenAPI.
* Include actions to sync on every push to master
* Allows for modyfing descriptions freely on the online editor, while keeping type definitions on code.
* Implements 2 API specs, one for default and one for walrus. Each with an example  endpoint for referencing when continuing docs with other endpoints.
* As a future enhancemente, we could consider using Marshmallow schema classes to define type on Python and autogenerate them with the flassger tool.
https://github.com/flasgger/flasgger#using-marshmallow-schemas
You can see the result of docs here, combined with a manually added success alert box: https://diffgram.readme.io/reference/post_api-v1-project-project-string-id-discussion-discussi …
=> feat: CORE-26 Autogenerate OpenAPI Docs from Code

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue
Fixes complete hotykey on tasks. Now you can complete task by doing shift +C
I have...
I have...
=> fix: complete hotkey

frontend/src/components/attribute/attribute_group_list.vue
=> Prevent call to fetch global attributes if there no project string id

frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/base/attribute_preview.vue, frontend/src/components/base/standard_chip.vue
=> Add Attribute preview to the image interafce

frontend/package.json, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/media_core.vue, frontend/src/components/base/standard_chip.vue, frontend/src/components/discussions/issues_sidepanel.vue, frontend/src/components/label/label_select_annotation.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/source_control/file_manager_sheet.vue, frontend/src/components/source_control/file_preview.vue, frontend/yarn.lock, shared/database/point_cloud/point_cloud.py, shared/url_generation.py
* Removes thumbnail generation from connection ID context using external signer.
* Removes duplicate calls to labels and instance list in task context and files context.
* Removes signed url generation in task context and instance list context.
I have...
I have...
=> Fix Optimize Duplicate Calls and File Fetch Speed

shared/project_migration/ExternalMigrationManager.py
Fixes incorrect param name on migration manager
I have...
I have...
=> Fix: Param Rename on MigrationManager

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/vue_canvas/v_bg.vue, frontend/src/helpers/task/TaskPrefetcher.ts
=> Image prefetcing

default/methods/task/task_template/job_list.py, default/tests/methods/task/task_template/test_job_list.py, frontend/src/components/task/job/job_list.vue
=> Feat job pagination

frontend/src/components/concrete/dataset/dataset_selector.vue, frontend/src/components/source_control/dataset_explorer.vue
=> Fix dataset multiple select

frontend/src/components/attached/global_dataset_selector.vue, frontend/src/components/concrete/dataset/dataset_selector.vue, frontend/src/components/project/settings.vue
=> Add show ids

shared/alembic/versions_opencore/alembic_2022_11_15_12_24_f1b006dd9e9e_add_index_to_the_job_table.py
=> Add indexes to the job table

frontend/cypress/e2e/diffgram/annotate_files/10_advanced_settings.cy.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/regular/button_with_menu.vue, frontend/src/components/vue_canvas/target_reticle.vue
=> Fix rendering on task context

frontend/src/helpers/task/TaskPrefetcher.ts
=> Fix prefetching bug pointed on the call

frontend/src/components/annotation/annotation_core.vue
Remove box old legacy code.
I have...
I have...
=> cleanup: removes all box creation legacy code

.github/workflows/e2e_tests.yaml, frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js, frontend/cypress/support/commands.js, frontend/src/components/annotation/media_core.vue, frontend/src/components/attribute/attribute_group.vue
fix: populate default value in multi select
I have...
I have...
=> fix: populate default value in multi select

frontend/src/components/annotation/media_core.vue, frontend/src/components/task/job/job_select.vue, shared/helpers/sessionMaker.py
Job list fix 
I have...
I have...
=> Fix: job list API call

frontend/src/components/annotation/annotation_core.vue
=> Force updating attributes on the global instance

default/methods/report/custom_reports/TaskReportRejectRatioReport.py
=> Fix: Approval Reject Report 

docker-compose.yaml
fix: remove folder removal line
I have...
I have...
=> fix: remove folder removal line

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/helpers/InstanceStore.ts
=> Instance store video context

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/label/label_select_annotation.vue, frontend/src/components/vue_canvas/coordinators/coordinator_types/ImageAnnotationCoordinator.ts
* Adds hotkeys from 1-9 for selecting elements on radio buttons
* Changes hotkeys for labels to shift+[0-9]
I have...
I have...
=> AI-51: Add Hotkeys To Radio Button

frontend/cypress/e2e/diffgram/3d_interface/01_show_3d_point_cloud.cy.js, frontend/src/App.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/vue_canvas/coordinators/ImageAnnotationCoordinatorRouter.ts, frontend/src/components/vue_canvas/coordinators/coordinator_types/BoxInstanceCoordinator.ts, frontend/src/components/vue_canvas/coordinators/coordinator_types/ImageAnnotationCoordinator.ts, frontend/src/components/vue_canvas/coordinators/coordinator_types/KeypointInstanceCoordinator.ts, frontend/src/components/vue_canvas/coordinators/coordinator_types/PolygonInstanceCoordinator.ts, frontend/src/components/vue_canvas/instances/BoxInstance.ts, frontend/src/router/router.js, frontend/src/types/InteractionEvent.ts, frontend/tests/unit/annotation/annotation_core.spec.js
=> Fix Typescript and Tests

frontend/src/components/geo_annotation/geo_annotation_core.vue
=> Geo annotation improvements 

default/methods/report/report_runner.py, default/methods/stats/stats.py, frontend/src/components/report/CSVReportFormatter.ts, frontend/src/components/report/report.vue
Little fixes in reporting:
* [Add All for task status](https://github.com/diffgram/diffgram/commit/0563635368fdffcf3ecdfb3534c7ec7bdc6d39df) 
Because otherwise other reports for group by don't work
* [Refactor: disambiguate between values and values metdata](https://github.com/diffgram/diffgram/commit/d74021263af83d5fed53e5a56c4cec90f60d67b7)
* [Fix assumption on second group by](https://github.com/diffgram/diffgram/commit/437c69058469ef3d551df28692b1f2680a920492)
* added docs for Double group by report https://diffgram.readme.io/docs/double-group-report
I have...
_All items are required. Please add …
=> Fix: Little fixes in reporting

frontend/src/components/report/annotator_performance.vue, frontend/src/components/report/approval_reject_ratio.vue, frontend/src/components/report/task_time_spent.vue, frontend/src/components/report/tasks_count_per_user.vue, frontend/src/components/report/tasks_percentage_user.vue, frontend/src/components/stats/stats_panel.vue, frontend/tests/unit/stats/stats_panel.spec.js, shared/database/task/task.py
=> Fix insights panel

walrus/methods/geotiff/GeoTiffProcessor.py
=> Re-project geotiff to EPSG:3857 on upload

frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/attribute/global_attributes_list.vue, frontend/src/components/geo_annotation/geo_annotation_core.vue, frontend/src/components/geo_annotation/geo_sidebar.vue, frontend/src/components/geo_annotation/geo_tile.vue, frontend/src/components/geo_annotation/geo_toolbar.vue, frontend/src/components/text_annotation/text_annotation_core.vue, frontend/src/components/vue_canvas/instances/GeoInstance.ts, frontend/src/services/attributesService.js, walrus/methods/geotiff/GeoTiffProcessor.py
=> New geo interface functionality

default/methods/report/report_runner.py, frontend/src/components/report/report.vue
Fix UI rendering for null cases
=> Report fix null case

frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/annotation/sidebar_factory.vue
* moved interface_type to annotation_ui_factor as it might be used by sidebar and toolbar too.
* fixes reactivity issues with attributes.
* Added getter for current annotation_ref and current sidebar_ref
I have...
I have...
=> Add Sidebar Fixes For Annotation Area and Attributes Updates

frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/sidebar_image_annotation.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/source_control/compound_file_preview.vue, frontend/src/types/AnnotationUIContext.ts
* Removes current_file concept, now only current_file exists.
* Adds working_file_list for compound file management.
* Adds placeholder components for empty compound files.
I have...
I have...
=> Unify Current Working FIle and Current File

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue
=> Fix instance list updating logic

shared/export/export_generation.py
=> Add relations to the text export

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/geo_annotation/geo_annotation_core.vue, frontend/src/components/annotation/panel_manager.vue
=> Small fixes for the Geo Interface

frontend/src/components/annotation/annotation_ui_factory.vue
=> Fix reading keydown of undefined console error

frontend/src/components/annotation/text_annotation/text_annotation_core.vue
…s assigned
...
I have...
I have...
=> Allow drawing text instances with different labels

frontend/src/components/annotation/text_annotation/text_annotation_core.vue
=> Fix free text attribute on the text interface

frontend/cypress/e2e/diffgram/annotate_files/09_data_integrity.cy.js, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/panel_manager.vue, frontend/src/components/annotation/panel_manager_toolbar.vue, frontend/src/components/annotation/panel_manager_width_height_controls.vue, frontend/src/components/annotation/panel_metadata.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/services/attributesService.js, frontend/src/types/AnnotationUIContext.ts, frontend/src/types/attributes/PanelsSettings.ts, frontend/src/types/mouse_position.ts, frontend/src/utils/instance_utils.ts, walrus/methods/input/packet.py
Adds grid support for compound files.
I have...
I have...
=> CORE-61 Add Grid Support For Compound Files

.github/workflows/update_readme.yaml, default/docs/file_update_metadata.yml, default/methods/source_control/file/file_update_metadata.py, frontend/package.json, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/panel_metadata.vue, frontend/yarn.lock, shared/alembic/versions_opencore/alembic_2023_02_03_15_55_0a4fd483f722_add_ordinal_to_files.py, shared/database/input.py, shared/database/source_control/file.py, shared/database/video/video.py, walrus/methods/geotiff/GeoTiffProcessor.py, walrus/methods/input/packet.py, walrus/methods/input/process_media.py, walrus/methods/sensor_fusion/sensor_fusion_file_processor.py, walrus/methods/video/video.py
Adds ordinal management to compound files.
I have...
I have...
=> feat: add ordinal management to compound files

.github/workflows/e2e_tests.yaml, frontend/build/webpack.base.conf.js, frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js, frontend/cypress/e2e/diffgram/annotate_files/09_data_integrity.cy.js, frontend/package.json, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/types/AnnotationUIContext.ts, frontend/yarn.lock, local_dispatcher/local_dispatch.py, walrus/methods/input/process_media.py
Removes dependency on `node-fibers` package .
After this is merged, for any dev environments. It is suggested that you delete your `node_modules` folder and re run `yarn install`
I have...
I have...
=> feat: upgrade to add node 16 support

walrus/methods/input/upload.py
=> Add ordinal prop to from_local route

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/hotkeys.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/label/label_select_only.vue, frontend/src/components/regular/button_with_menu.vue, frontend/src/types/InteractionEvent.ts
Use cltr+ arrows to change selected instance
Use L to open change label menu,
Select label with up/down arrows + enter to close
I have...
I have...
=> Select and Changel Labels with Hotkeys

install.py
Fix installation checks for azure to set minio checks to false.
I have...
I have...
=> Fix Install checks for azure/minio

default/play_and_scripts/update_attributes_test.py, frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js, frontend/cypress/e2e/diffgram/text_interface/01_annotate_text.cy.js, frontend/package.json, frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/hotkeys.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/annotation/image_and_video_annotation/sidebar_image_annotation.vue, frontend/src/components/annotation/panel_manager.vue, frontend/src/components/annotation/sidebar_factory.vue, frontend/src/components/annotation/text_annotation/text_annotation_core.vue, frontend/src/components/annotation/text_annotation/text_sidebar.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/attribute/global_attributes_list.vue, frontend/yarn.lock
* Adds attribute hotkeys
* Improves sidebar displays for attributes
* Fixes display bug when changing files from the bottom bar.
*Adds attribute IDs by default on schema section
I have...
I have...
=> CORE-91 add hotkeys, improve display sidebar 

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue, frontend/src/types/AnnotationUIContext.ts, shared/database/task/job/job.py, shared/database/task/task.py
* Fix query for next task endpoint to inlcude in progress tasks.
* Fix stats endpoint to include in progress tasks.
I have...
I have...
=> Fix: Next tasks query fixes & make stats count in progress tasks.

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/text_annotation/text_annotation_core.vue, shared/query_engine/grammar.py
Fix: adds support for question marks in dataset explorer.
fix: fixes opening text files from dataset explorer.
=> Fix: Support question marks on dataset explorer

frontend/src/components/annotation/3d_annotation/sensor_fusion_editor.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue, frontend/src/components/ui_schema/action_configs/action_config_renderer.vue, frontend/src/components/ui_schema/action_configs/attribute_set_value_config.vue, frontend/src/components/ui_schema/button_edit_action_step.vue, frontend/src/components/ui_schema/button_edit_context_menu.vue, frontend/src/components/ui_schema/button_workflow_editor.vue, frontend/src/components/ui_schema/custom_buttons_section.vue, frontend/src/components/ui_schema/ui_schema_context_menu.vue, frontend/src/store.js, frontend/src/types/AnnotationUIContext.ts, frontend/src/types/ui_schema/BaseActionCustomButton.ts, frontend/src/types/ui_schema/Buttons.ts, frontend/src/types/ui_schema/CustomButtonWorkflow.ts, frontend/src/types/ui_schema/button_actions/ActionCompleteTask.ts, frontend/src/types/ui_schema/button_actions/ActionSetAttributeValue.ts, frontend/tests/unit/3d_annotation/sensor_fusion_editor.spec.js
=> Multi Action Custom Buttons

default/methods/configs/get_version.py, default/methods/task/task_template/job_resync.py, default/routes_init.py, frontend/src/components/annotation/3d_annotation/sensor_fusion_editor.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/file_meta_data_card.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue, frontend/src/components/source_control/dataset_explorer.vue, frontend/src/components/ui_schema/action_configs/action_config_renderer.vue, frontend/src/components/ui_schema/action_configs/attribute_set_value_config.vue, frontend/src/components/ui_schema/button_edit_action_step.vue, frontend/src/components/ui_schema/button_edit_context_menu.vue, frontend/src/components/ui_schema/button_workflow_editor.vue, frontend/src/components/ui_schema/custom_buttons_section.vue, frontend/src/components/ui_schema/ui_schema_context_menu.vue, frontend/src/store.js, frontend/src/types/AnnotationUIContext.ts, frontend/src/types/ui_schema/BaseActionCustomButton.ts, frontend/src/types/ui_schema/Buttons.ts, frontend/src/types/ui_schema/CustomButtonWorkflow.ts, frontend/src/types/ui_schema/button_actions/ActionCompleteTask.ts, frontend/src/types/ui_schema/button_actions/ActionSetAttributeValue.ts, frontend/tests/unit/3d_annotation/sensor_fusion_editor.spec.js, shared/alembic/versions_opencore/alembic_2023_05_02_10_31_3588f18b378f_add_time_created_and_annotation_.py, shared/database/task/task.py, shared/query_engine/expressions/file.py, shared/query_engine/sql_alchemy_query_elements/file.py, shared/utils/job_dir_sync_utils.py, shared/utils/task/task_update_manager.py
=> Query Explorer: support created time and ann_is_complete

frontend/package.json
remove: nightwatch dependency
I have...
I have...
=> remove: nightwatch dependency

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/task/job/job_file_routing.vue
[Fix: Completing a task was showing Next task as complete wrongly](https://github.com/diffgram/diffgram/commit/7371ec15b01006ad4d6e495ad0763b792dbac74a)
=> Fix task status

default/methods/task/task_template/job_new_or_update.py, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue, frontend/src/components/annotation/text_annotation/text_annotation_core.vue, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/ui_schema/custom_buttons_section.vue, frontend/src/components/vue_canvas/CanvasMouseTools.ts, frontend/src/components/vue_canvas/advanced_tools/PolygonAutoBorderTool.ts, frontend/src/types/image_label_settings.ts
Fixes a number of UI bugs and performance items, especially:
* [Important connection for core to sidebar](https://github.com/diffgram/diffgram/commit/fdfb2092e94b4e9362b2cd826afcb0cec2eb3851)
* [Fix if instance values are not yet defined](https://github.com/diffgram/diffgram/commit/775b9c2f93efc1cebf00409fb4204a53fd8b8025)
* [Use large_annotation_volume_performance_mode](https://github.com/diffgram/diffgram/commit/e03b176761ad39adaab36cef7006069de46ec20f)
=> UI improvements boxes

frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue
Note this feature will require some more updates to be Preview ready
=> Enable Annotation Show V0 in new Context

README.md, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/instance_detail_list_view.vue, frontend/src/components/attribute/global_attributes_list.vue, frontend/src/components/base/attribute_preview.vue, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/label/label_select_only.vue, frontend/src/components/task/task/task_list.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/components/vue_canvas/instances/BoxInstance.ts, frontend/src/components/vue_canvas/instances/InstanceImage2D.ts, frontend/src/components/vue_canvas/instances/PolygonInstance.ts, frontend/src/vue-canvas.js
1. Adds context menu label change, in context of new performance mode (less on side bar, better UI/UX)
2. Fixes timing issue when drawing box
3. Align issues UI drawing to new context
4. General clean up, small UI alignment and fixes
Especially these commits:
[Add label select change from context menu](https://github.com/diffgram/diffgram/commit/cf558ca24d5310b53ee5794776ba6f5734be9e2d)
[Fix timing issue setting color on box](https://github.com/diffgram/diffgram/commit/e4850375f160d9cd0f6af6d49959baa6590b1af5)
[Align with new annotation_ui_context paradigm](https://github.com/diffgram/diffgram/commit/4f5a6b3ae4bf9c580a551af8a6628d322346d287)
[Upgrade to issues_ui_manager paradigm](https://github.com/diffgram/diffgram/commit/7d9bf241ebfd08ebaca2d9e823d0b7994d7a3dd3)
=> Add label context menu & UI/UX improvements

default/methods/task/task/task_list.py, frontend/cypress/e2e/diffgram/compoundfile_global_attritbutes/01_compound_global_attribute.cy.js, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/regular/diffgram_select.vue, frontend/src/components/report/report.vue, frontend/src/components/share/share_new_member.vue, frontend/src/components/task/task/task_list.vue, frontend/src/components/user/home/annotator_dashboard.vue, frontend/src/services/tasksServices.js
- Add preview and counts in homepage mode by -> [Refactor to Task updates to services](https://github.com/diffgram/diffgram/commit/39eb52292118347b1439f63c113898b75cfe74f0)
- [Upgrade Permissions selector](https://github.com/diffgram/diffgram/commit/5c3438e6327ffd4aae0f73c5cbe0fed8bc8dabba)
- Little clean ups
- [Improve spacing for annotation in full single image mode](https://github.com/diffgram/diffgram/commit/f6f5a67ac9e72333faff05c9c3e50a2df846c975)
logged panel spacing items here
https://github.com/diffgram/diffgram/issues/1411
=> Improve: Task Preview, Permissions selector, Image Spacing

frontend/src/components/vue_canvas/v_bg.vue
fixes https://github.com/diffgram/diffgram/issues/1438
=> draw png background

shared/alembic/versions_opencore/alembic_2023_07_03_23_32_2ef6ace7da75_improve_input_indexes.py, shared/database/input.py, shared/permissions/api_permissions.py, shared/utils/cpu_checks.py, walrus/methods/input/process_media_queue_manager.py
* [Refactor adding RemoteQueue class](https://github.com/diffgram/diffgram/commit/27e10063e480719707940b825be66d18e9ee46b0)
-> Add remote queue class to better seperate remote queues and related functions
-> Better controls remote queues and better flexibility. for example different times on each.
-> Pulls auto retry out of other assumptions on media processing
-> Refactor start() into functions for cleaner reading
* [Add CPU wait and check](https://github.com/diffgram/diffgram/commit/123e9f2cffc0702704c780439a3cc6da01c22898)
* [Improve indexes on input table](https://github.com/diffgram/diffgram/commit/de0b9240f6530dfb544bc2b1ba11d606e02bd2a9)
-> fix existing index to align with alembic definition of `processing_deferred` not `archived`
-> Add other indexes, context of new versions of …
=> Performance improvements

default/methods/user/account/account_new.py, docker-compose.yaml, frontend/src/components/annotation/image_and_video_annotation/labels_edit.vue, frontend/src/components/annotation/image_and_video_annotation/labels_new.vue, frontend/src/components/user/edit.vue, install.py, local_dispatcher/local_dispatch.py, shared/data_tools_core_minio.py
[Big Rewrite of Dispatcher to Ingress](https://github.com/diffgram/diffgram/commit/ca50d9bd948ea19a5728b1d31c60c81919745b93) 
-> Now everything is in classes
-> There is a default Ingress class
-> There is a DockerIngress example, that only changes things needed for docker context so it's crystal clear what's being changed
-> A user can now easily define new services, or choose which services are local, docker, or even remote
-> Removes lots of noise from logs. New logs are clear which service and ingress is being used, and the complete URL with port that's being called
-> Docker context is now more clearly assumed vs same host assumptions
- [remove label rules to allow special chars 你好](https://github.com/diffgram/diffgram/commit/f08d6b4f89c69077c8aa3ba7e6f712a4045d2656)
- General clean …
=> Rewrite Dev Ingress (Dispatcher), Allow Special Chars, General Maintenance 

frontend/package.json, frontend/src/components/annotation/audio_annotation/render_elements/waveform_selector.vue, frontend/yarn.lock
Update wavesurfer from v6 to v7.
[GitHub Issue](https://github.com/diffgram/diffgram/issues/1465)
I have...
* [X ]  provided a link to the relevant issue in JIRA or Github Link in PR.
* [ X]  reviewed "Files changed" and left comments if necessary
I have...
=> Update vawesurfer to v 7

shared/database/event/event.py
Restore missing settings check.
=> Restore eventhub setting
