sdk/diffgram/core/core.py
Context is that users with diffgram on-prem need to specify the host of their instance in order for the SDK to work with them.
I don't  feel there are other changes to do here, but let me know if the onprem changes touch other scopes of the sdk that I have not considered.
=> Add Host To Project Paramaters

sdk/diffgram/file/file_constructor.py
To prevent the backend from triggering alerts.
=> Add duplicate ID's validation on the client

README.md, default/methods/images/images_core.py, walrus/methods/machine_learning/semantic_segmentation.py
This for better support of the other third party cloud providers and overall improvement of code abstraction.
=> Migrate Profile Picture Upload to Use DataTools()

.gitignore, default/methods/report/report_runner.py
Context that `stats.copy()` throws exception if stats is None
=> (tiny) Fix report

docker-compose.yaml, install.py
Now the install script will ask the user for 2 new options:
1. The Diffgram version tag, by default it will point to the latest version tag.
2. The postgres database url, which will populate `DATABASE_URL` parameter and conditionally change the image tag of postgres to a `scratch` docker image that does nothing (so we have no postgres installed)
=> Add External DB To Install Script

walrus/methods/connectors/labelbox_connector.py
Error context:
```
KeyError: 'result'
at add_files_to_labelbox_dataset (/app/methods/connectors/labelbox_connector.py:707)
at wrapped (/app/methods/connectors/labelbox_connector.py:249)
at send_all_files_in_task_template (/app/methods/connectors/labelbox_connector.py:792)
at wrapped (/app/methods/connectors/labelbox_connector.py:258)
at wrapped (/app/methods/connectors/labelbox_connector.py:249)
at execute_after_launch_strategy (/pp/methods/task/task_template/task_template_after_launch_strategies/labelbox_task_template_after_launch_strategy.py:242)
```
Issue is fixed on this PR, just needed to convert to string the external ID.
=> fix: Labelbox API now expect string in the external ID's

default/methods/user/account/account_verify.py
Context is that in some cases the base domain does not end with a slash and in some cases it does. So handling both cases here.
=> bugfix: small fix on building url to append a slash when non-existent.

README.md, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/ghost_canvas_available_alert.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/annotation/media_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/discussions/create_issue_panel.vue, frontend/src/components/label/label_select_annotation.vue, frontend/src/components/video/sequence_list.vue, frontend/src/components/vue_canvas/ghost_instance_list.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/components/vue_canvas/instances/Instance.ts, frontend/src/store.js, shared/alembic/versions_opencore/alembic_2021_05_17_21_32_c3d95120b9ce_add_pause_object.py, shared/annotation.py, shared/database/annotation/instance.py
New "Ghost" instance proposals make it 10x easy to annotate for both casual and pro users.
Now, a user doesn't really need to understand anything about sequences to use sequences.
As a user I can draw the the objects.
The system presents context that I can choose to accept or ignore.
There is no need to expressly "decline" proposals, all proposals are declined by default.
New "Ghost" proposals. Ghost proposals are generated on frame change. Crucially
1) It's based on the last keyframe. A user can go at any pace, from frame by frame to jumping thousands of frames.
2) It's clearly different from normal instances. By using a seperate list and rendering mechanism, this is isolated from the normal instance list. This presents a better "middle ground" between our prior state of not showing …
=> 👻 Ghost Objects - Video Now 10x easier for new annotators 

install.py
On some docker versions scratch is a reserved word, giving errors to some users when pulling the images.
=> bugfix: change dummy image to tianon/true

frontend/src/components/annotation/userscript/userscript.ts, frontend/src/components/annotation/userscript/userscript.vue
This appears to resolve the timing issue
https://github.com/diffgram/diffgram/issues/72
Now it appears to be waiting until the first script is loaded before loading the next one.
It looks like the function was getting called twice for some reason, causing it to essentially ignore the await block.
=> Add Userscript loading guard

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/label/label_select_annotation.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/regular/diffgram_select.vue
- Now toolbar has a full screen width and the entire app has white bg to make it more consistent. 
- Also fixed some spacing issue with the label select and instance type select which made the borders look a bit weird.
- Removed black border of the canvas on the "focus-visible" state.
Before
After:
=> Improve UI styles of toolbar

frontend/src/components/project/settings.vue, walrus/methods/video/video.py
Removing logic and now just leaving the default to 1 so no conversion is performed.
=> Deprecate video framerate conversion

frontend/src/components/task/job/job_list_card_display.vue
Added some custom css to better handle text wrapping
=> Fix job card title styles for long text

frontend/src/components/input/input_payload_dialog.vue, frontend/src/components/input/input_view.vue, shared/database/input.py, walrus/methods/input/input_view_detail.py, walrus/methods/input/process_media.py
When processing an update and receiving an empty frame packet map in the video case, the input status was stuck at "processing" and never failed.
=> Add error condition when frame packet map is empty in update case

walrus/methods/input/process_media.py
Error should be a dict and not a string value.
=> Better handle errors in updating from frame packet map.

walrus/methods/input/process_media.py
When the original file name cannot be determined the walrus should not crash but just ignore type extraction.
=> fix: extension extraction validation over None types

frontend/src/components/input/upload_summary.vue, frontend/src/components/input/upload_wizard_sheet.vue
The file filter was looking for the file name instead of the ID causing the instances to be created on all the files because of the lack of filtering
=> Fix Instance Filters For Update Case UI Wizard

frontend/src/components/annotation/annotation_core.vue
This problem did not occured often, but was able to figure it out the following way:
Since we are persisting the vuex store, there is a chance that we can refresh the screen while `set_user_is_typing_or_menu_open` is `true`. For example, refreshing the screen while creating an issue. This creates an invalid initial state which makes hotkeys stop working because the flag was not resetted. 
Now this is fixed by resetting `set_user_is_typing_or_menu_open` on the mounted function of annotation core.
=> fix: Hotkeys bug with vuex

default/tests/conftest.py, default/tests/shared/database/model/test_model_run.py, walrus/tests/conftest.py
This allows us to indirectly test that the migrations have been done correctly setup and that we can guarantee creating the DB from scratch with the current migrations that exist in the codebase.
=> Make use of alembic inside test context too.

frontend/src/components/video/video.vue
The problems was due to getBoundingRectClient() getting different target elements since there are multiple listeners. So i changed it to use currentTarget instead of target which changes to the element that actually has the listener so it stays with the same width all the time and stops causing that bouncing effect.
=> Fix preview frame bounce

frontend/src/components/annotation/task_meta_data_card.vue, shared/utils/task/task_complete.py
I'm changing this to completed once they click complete again as it's the more straightforward way of going about it. We can discuss the ideal way to manage the review states in the future or even discuss if those states are necessary at all now that we have the issues system.
=> fix: in review state has no way to complete.

frontend/package.json, frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/instance_schema_mapper.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_wizard_sheet.vue
I realized this is going to be a necessary step if we want to support more standard data formats like tensorflow or pytorch json format since they all use nested values on the ouput jsons. This way people can just download the standard coco dataset for example and reupload it to diffgram with the wizard or via the connections system.
=> Add support for nested keys in JSON

shared/annotation.py
Otherwise annotation_update is not available and raises an unhandled exception.
=> fix: stop execution when having an exception on instance_list processing

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/label/label_select_annotation.vue
current labels is undefined if not label templates have been created on the project. I also added a link to the label creation section when clicking the empty label list selector.
=> fix: when no label templates available there was an unhandled exception.

frontend/src/components/input/input_view.vue, frontend/src/components/input/new_or_update_upload_screen.vue, walrus/methods/input/process_media.py, walrus/methods/input/upload.py
So users can see which inputs where created from the wizard:
=> Added source from UI wizard

shared/annotation.py, shared/utils/logging.py
Default to the standard stdout logging mechanism.
This was causing issues with users that were not using GCP as their default credentials. We should not assume any providers were configured at startup and at the logging context. Now we are going to default to the stdout logging and we can add new mechanisms or configurations to send logs to an external provider.
=> Bugfix: In production context, default to not using gcp logger

frontend/src/components/input/file_schema_mapper.vue, walrus/methods/input/process_media.py
The context is that since queues are fetched by multiple threads at the same time. We can get a chance were 2 threads process the same item. We add a thread lock to both the frame and the video queue to prevent this from happening as an exception raised at this level can halt the entire system and require a restart.
=> fix: make process media thread safe with locks

default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/media_core.vue, frontend/src/components/source_control/dataset_explorer.vue
The idea is to remove the boolean request_next page and just build the pagination mechanism based on the page number and the limit.
This is because now the pagination is going to be supported in the SDK and we need this working before we can implement the new SDK features.
=> Improve pagination on file list

default/methods/source_control/file/file_browser.py, default/methods/source_control/file/file_exists.py, frontend/src/components/input/file_schema_mapper.vue, frontend/src/components/input/new_or_update_upload_screen.vue, frontend/src/components/input/upload_summary.vue, frontend/src/components/input/upload_wizard_sheet.vue, frontend/src/utils/colorUtils.js, shared/annotation.py, shared/database/project.py
When the wizard does not find the labels, add a button to create all the missing ones so the user can continue with the flow.
This helps specially for big uploads where you would have to manually create 100s or 1000s of labels one by one. This button removes the need to create them manually.
=> Create Missing Labels on Upload Wizard

default/methods/batch/append_to_batch.py, default/tests/shared/query_engine/test_sqlalchemy_query_executor.py, frontend/src/components/input/upload_summary.vue, frontend/src/components/source_control/dataset_explorer.vue, shared/alembic/versions_opencore/alembic_2021_07_05_20_52_5b9176d6cdcf_add_temp_cloud_storage_fields.py, shared/data_tools_core_azure.py, shared/data_tools_core_gcp.py, shared/data_tools_core_s3.py, shared/database/batch/batch.py, shared/model/model_manager.py, shared/tests/test_utils/data_mocking.py
To avoid using local temp folders since uploads can fail if the deployment has multiple servers in a load balancer.
=> Save temp file in cloud storage

default/methods/batch/append_to_batch.py, frontend/src/components/input/upload_summary.vue, shared/database/batch/batch.py
For the case of huge payloads we will not save them on postgres and only save the cloud url since postgres columns max size is 1gb
=> Add get prelabeled data from cloud on Batch Objects

shared/alembic/versions_opencore/alembic_2021_07_09_08_38_9192f806a8cb_add_unique_together_to_frame_numbers.py, shared/database/source_control/file.py
Idea is to prevent the DB to have an undesired state by limiting a unique frame number per video parent file id.
- This will mitigate the issue of having to threads process the same video (due to users retrying the same video 2 times or more)
=> Add a unique constraint for frame numbers in video files

frontend/src/components/input/upload_wizard_sheet.vue
UI issue made counter not update correctly on large videos. Now we keep a separate counter per file upload ID and add them up on a computed prop
=> Upload progress was not updating properly

default/methods/query_engine/query_suggest.py
This endpoint can work for public projects, so in some cases request.authorization can be None.
=> Check for request authorization on query suggest

shared/helpers/sessionMaker.py, shared/settings/settings.py
So users can tweak the number of connections for better scalability and performance
=> Add connection pool size setting

frontend/src/components/vue_canvas/instance_list.vue, shared/database/source_control/file.py
Now Data Explorer instances display the same label color as in the editor.
=> Show Instance Colors Data Explorer

frontend/src/components/user/account/user_password.vue
append-icon-cb was deprecated and causing this function to not work
did manual test and appears to be working as expected
context is that now that we default to requiring password, this was preventing a user from copying and pasting or inspecting their password.
this is a small bug fix will merge once tests pass
=> Small bug fix - upgrade to latest call back

frontend/src/components/input/input_view.vue
Quick fix:
Removed the alert on retry log as it can break some styles of the table.
Just a visual thing, the error alert can make people thing an error has happened when it really is just more info on the upload status.
=> Removed the alert on retry log input table

default/tests/shared/test_annotation.py, frontend/cypress/integration/diffgram/annotate_files/annotate_files_data_integrity.js, shared/annotation.py
In some cases the frontend can have unexpected bugs which makes the instance_list to not be sent completely to the backend.
Old versions assume that if instance was not present, it should be deleted, which caused unexpected silent deletion in some cases.
Now we double check that all the instances are available on the request payload before executing any logic in Annotation_Update
=> Prevent Silent Deletion of Instances in Annotation_Update

default/methods/source_control/file/file_cache_regen.py, default/routes_init.py, default/tests/methods/source_control/file/test_file_cache_regen.py, default/tests/shared/test_annotation.py, frontend/cypress/support/commands.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/instance_detail_list_view.vue, frontend/src/components/regular/regular_error_handling.js, shared/annotation.py, shared/database/source_control/file.py
This improvements build on top if 2 realizations:
- If the file cache was manually/maliciously corrupted via a script, direct sql, etc. The user can get in a state where the file cannot be saved.
- If for some reason the file has was not regenerated re-saving the file won't soft delete  it.
So basically adding 2 additions:
1) Add a reload and regenerate cache button, so that if the above case happen at leas there is a way for the user to get back the correctly saved data and get back to annotating.
2) When we find a case of an instance not existing in the cache, we regenerate the hash to prevent the case where the instance does not match the hash, that way when the user refreshes and saves again the instance should have the correct hash.
=> Silent Deletion Improvements

walrus/methods/export/export_generation.py
Removed the .mp4 extension for cases different from gcp.
=> Fix malformed urls for Blob Storage on Exports

frontend/src/components/vue_canvas/instance_list.vue
When instances have no opacity, add a white border line to differentiate between instances.
=> Add borders in solid case

frontend/src/components/annotation/annotation_core.vue
This happens when the user does not save the file and changes the frame. Since the update algorithm always updated the instance_list, and the frame number has changed. The instance_list now corresponds to another frame, so now we pass the requests video data to check which was the frame that was saved and update the buffer dict accordingly.
=> Update frame buffer dict if frame was changed during save

default/methods/annotation/annotation.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/userscript/userscript.vue, frontend/src/components/video/video.vue, shared/annotation.py, shared/database/annotation/instance.py, shared/database/source_control/file.py, walrus/methods/input/process_media.py, walrus/methods/video/interpolation.py
To reduce cache errors occurrences:
1. Added the with_for_update() to instance list
2. Await the save method on frame changes instead of a sleep() time as sometimes the sleep can be less than the time the update takes, specially on slow connections.
=> fix: avoid race conditions and concurrent updates on annotation update

default/methods/source_control/file/file_cache_regen.py, default/tests/shared/test_annotation.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/regular/error_multiple.vue, shared/annotation.py, shared/database/annotation/instance.py, walrus/methods/input/process_media.py
Fixes 4 things:
1. Remove with_for_update on process_media to allow parallel processing.
2. Add remove collisions function to instance list existing
3. Soft delete existing colliding hashes on frontend instance list.
4. Add duplicate validation on frontend
=> fix: cache error fixes duplicate hashes

frontend/cypress/integration/diffgram/annotate_files/annotate_files_video_annotation_tools_spec.js, frontend/src/components/annotation/annotation_core.vue
Before, when users changed frames fast and the save operation took longer than the frame change. They could end up with frames not being saved, this because we only had one global `save_loading` flag per video.
Now we have added the `save_loading_frame` dict to control which frames are saving and not block other frames from saving if a save operation is occuring in another frame
Another bug that in the `add_ids_to_new_instances_and_delete_old` function were were using the reference to this.instance_list instead for the `frame_buffer_dict[request.video_data.current_frame]`. This could cause problems because this.instance_list can change while the annotations are saving. 
Please let me now what you think of these changes and if there's any issue/concern that stands out.
=> Add Per Frame Save Loading Flags

default/methods/user/account/auth_code.py, default/methods/user/account/magic_login.py, frontend/cypress/support/commands.js, frontend/src/components/user/home/dashboard.vue, frontend/src/components/user/login.vue
Context of debugging -> user not being able to use magic login.
I was unable to reproduce the error - even with an "empty" new user. However I did notice it was possible to get into odd UI states. That could be confusing.
For example if, as a user, I click the back button after doing the magic redeem, it would show this which was confusing.
1. Added a guard to prevent running auth if user is already logged in
2. Show state of already logged in
I believe solution is ok. 
An alterative is a navigation guard to prevent entry to this page. Because we use `beforeEnter` , at a quick analysis it seemed like it would have required bigger scope of changes to capture the `back` context. https://stackoverflow.com/questions/50087164/vue-router-how-to-prevent-the-user-back-to-the-login-screen-pressing- …
=> Login improvements - small

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Fixes this:
To reproduce in prior code, zoom in high amount eg 700%+ and move keypoints
=> Improve keypoints

default/main.py, shared/error_handlers/error_handlers.py, walrus/main.py
The exception handle we added was catching all types of exceptions. But we need to make a special case for the Forbidden exception since it's a different status code. 
From inspecting the code the are no other types of exceptions other than IOError, but that one should be handled as a 500. I think the general route should be to default to 500 and handle special types of exceptions with other handlers in this file.
=> fix: handle Forbidden exceptions correctly

default/methods/source_control/file/file_browser.py, default/methods/task/task_template/job_new_or_update.py, shared/regular/regular_log.py, shared/utils/job_dir_sync_utils.py, walrus/methods/connectors/azure_connector.py, walrus/methods/connectors/google_cloud_storage_connector.py, walrus/methods/connectors/s3_connector.py, walrus/methods/export/export_generation.py, walrus/methods/export/export_utils.py, walrus/methods/export/export_view.py, walrus/methods/export/export_web.py, walrus/tests/methods/export/test_export_generation.py
Summary
1. **Make export from tasks work as expected.** Meaning it pulls from tasks not files. This is becuase now that we have streaming, the concept of a file being associated with a singular job is ill-defined. Further it opens the ability to use task orientated filters!
2. It also happens to fix the one-off case of job_id not being populated unless annotation was completed, effectively meaning "ann_is_true" was forced on, but without actually using that flag, which is of course bad.
3. Fix a variety of > instead of >= and refactor to avoid in future. 
Note: It's possible this could have downstream effects, but unless there was some reason (I can't think of one) that we actually did want ">" for these, then this fix should still be correct, and we can do further fixes for downstream …
=> Upgrade export task context and general export fixes

walrus/methods/input/process_media.py
=> fix: duplicate file search query

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/hotkeys.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/context_menu/context_menu.vue, frontend/src/components/vue_canvas/CanvasMouseTools.ts, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, walrus/methods/data_mocking/generate_data.py, walrus/methods/input/process_media.py
Main work is an addition of this snap to instance feature described here:
https://diffgram.readme.io/docs/snap-to-annotation
There's a couple of rough edges but in general it appears to be working as expected.
Other items
1. Fixed generate samples -> was just missing filename for some reason
2. Increase zoom max -> user request, no clear reason we had it at number before
3. For Keypoints, option to have occluded keypoints hidden completely from view. This essentially makes them "deleted". and still leaves option to "undelete" them.
4. For Keypoints, enable mark point as _not_ occluded
5. Debugged that control key sticking issue a bit. Essentially the left control key seems to "stick", eg the keyup event never gets trigged. This seems to be some kind of odd ongoing issue. …
=> Snap to Instance and Keypoints improvements

frontend/src/components/annotation/toolbar.vue
1. Context that deferring a completed task is undefined
2. check == available instead of != complete because we may add other statues in the future.
=> Only show if available

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/vue_canvas/instance_list.vue
add draw_text() concept for font_background_opacity
Now we have a font background, and it's user selectable from 0 to 1
bugfix label_settings_local. this was a regression from refactor to component.
now updates in real time as user drags slider for all label settings
=> Annotation improvements

default/methods/annotation/annotation.py, default/methods/task/task/task_review.py, default/methods/task/task/task_update.py, default/methods/task/task_template/job_new_or_update.py, default/tests/methods/task/task_template/test_job_new_or_update.py, default/tests/shared/database/task/test_task_user.py, default/tests/shared/utils/task/test_task_assign_reviewer.py, default/tests/shared/utils/task/test_task_complete.py, shared/database/event/event.py, shared/database/task/job/job.py, shared/database/task/task.py, shared/database/task/task_user.py, shared/permissions/project_permissions.py, shared/regular/regular_member.py, shared/utils/task/task_assign_reviewer.py, shared/utils/task/task_complete.py
Adds the reviewer with the least amounts of tasks automatically as a reviewer when a user completes a task and the job supports reviews.
=> Auto Assign Reviewer on Task Completion

default/methods/task/task/task_complete.py, default/routes_init.py, default/tests/methods/task/task/test_task_complete.py, shared/annotation.py
Adds the endpoint:
`/api/v1/task/<int:task_id>/complete`
For more explicit and semantic URL when completing task on frontend.
=> Add task complete API endpoint

frontend/src/components/regular_concrete/task_status_icons.vue, frontend/src/components/stats/stats_panel.vue, frontend/tests/unit/regular_concrete/task_status_icons.spec.js, shared/database/task/task.py
In this PR:
- Display new icons for new statuses on the task list
- Display new statuses on the stats
=> Display new statuses on job page

frontend/src/components/annotation/annotation_core.vue
When pasting to next frames, if the selected next frames where not yet on the instance buffer dict, the pasted instance would overwrite the entire frame.
Now we fetch any missing frames beforehand to guarantee that the pasted frame  is added to the existing instance list.
=> fix: paste to next frames now fetches missing instance buffers

default/main.py, default/tests/shared/test_annotation.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/utils/AnnotationSavePrechecks.ts, frontend/src/components/free_tier_limits/free_tier_limit_dialog.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/video/sequence_list.vue, shared/alembic/versions_opencore/alembic_2021_12_15_11_15_e25f886d921a_add_member_created_id_to_input_table.py, shared/annotation.py, shared/database/source_control/file.py, shared/database/video/sequence.py, shared/feature_flags/feature_checker.py
1. **Backend**: Extract keyframe cache to be more composable. This splits the old and confusing thing hidden in the `update` calls into much more clear stuff ->
The main concept here is to make it easier to understand when keyframes are getting added or removed from the cache
https://github.com/diffgram/diffgram/commit/83b635759511c9ab3d1541b65f3175db88093d5b  (plus some little updates after)
**Timing bug**
There was a timing bug here too - depending on the order of it it was possible that the deletion would overwrite the addition.
eg ->  added instance adds frame number 29 then the removed version of it goes and deletes it. it's correct if the order is inverted. but order is hard to setup here. 
Solution was to just tracking which sequences we already added to, and then using that as an …
=> Improve sequence list

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/main_menu/menu.vue, frontend/src/components/video/video.vue
Removing the @input event from slider since it was causing frame changes problems with hotkeys. It seems that this event handler is executed only when the frame_number value changes so I think it's not necessary to have it at all.
=> Fix Frame Changes Bug

default/tests/shared/test_annotation.py, frontend/cypress/integration/diffgram/annotate_files/06_annotate_files_instance_drawing_spec.js, frontend/src/components/vue_canvas/cuboid.js, shared/annotation.py, shared/database/annotation/instance.py
When the hashing algorithm was changed, we were not able to differentiate between a new hash from a user edit, or a new hash from the new algorithm version. 
Now we rehash the entire existing instance_list to always have the latest version of the hash in place.
- Added a test case to replicate this issue
- Pending some more unit tests to check instance history is not getting corrupted.
=> Rehash Existing Instances to Prevent Instance History Corruption

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/video/video.vue, frontend/tests/unit/annotation/annotation_core.spec.js
Now images are getting fetched proactively on the buffer to avoid users waiting for networks requests.
- Added the `frame_image_buffer` which will hold all the images of the video that had already been fetched.
- Added the `fetch_next_images` function witch fetches 10 frames before and after the current frame and stores the images on the `frame_image_buffer`.
- Now whenever we change frames, we first check the cached images and if there is o images we do a fetch as a fallback. This is implemented on the `on_key_frame_loaded` function in `annotation_core`.
=> Add proactive frame fetching to video player

frontend/src/components/input/new_or_update_upload_screen.vue, walrus/methods/input/process_media.py
The upload wizard was always setting CSV as prelabeled data. Now if you select, that you will NOT add prelabeled data the CSV is considered as a list of URL's and uploaded correctly.
The CSV Provided was not working due to that page throwing 403 to anything that is not a web browser.
I added a new CSV where I removed 2 of the 3 rows to some other URL so you can re test the upload
[testcase - Dogs - testcase - Dogs.csv](https://github.com/diffgram/diffgram/files/7873488/testcase.-.Dogs.-.testcase.-.Dogs.csv)
=> Fix CSV Uploads

default/methods/batch/append_to_batch.py, frontend/src/components/input/upload_summary.vue, shared/data_tools_core_azure.py, shared/data_tools_core_gcp.py, shared/data_tools_core_s3.py
Batch object was missing the 
` batch.upload_aws_id = response['UploadId']`
for it to proceed with the batch upload of big prelabeled files.
=> Allow Batched Prelabels Upload With S3 Connectors

default/methods/report/report_runner.py, frontend/src/components/video/video.vue, frontend/src/components/vue_canvas/video_drawable_canvas.vue
Context is that user goes to the task list before annotation core.
If we don't cancel the requests, then the frames/video files of 15 tasks will be fetching while they open the annotation core video.
This was causing the requests from 15 videos to be queued, and when going to the video annotation this was consuming all the bandwith for the frames fetching
** Also includes small bugfixes to report runner
=> Cancel Frames/Video requests on video drawable canvas on destroy

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/video/video.vue
This only happened when video reached the end, causing an infinite loop and browser crashing
=> Fix Video: animation was not stopping even though video ended

docker-compose.yaml, install.py
Without this option the container doesn't work under Linux distros with Selinux
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
Windows seems to be unaffected by adding the :Z option
This fixes #580
=> Configure Selinux label

walrus/methods/input/process_media.py
I think the original file got uploaded instead of the thumbnail. Result is shown below (file 14 + thumb is old code, file 15 + thumb is the new code)
This will fix #592
=> Change file path from original file to the actual thumbnail file

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Now rotate point is placed correctly on the keypoint instance
Fixes: https://github.com/diffgram/diffgram/issues/560
=> DAD-43 fix: misplaced rotate point after drawing

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/discussions/create_issue_panel.vue, frontend/src/components/discussions/issues_sidepanel.vue, frontend/src/components/discussions/view_edit_issue_panel.vue, frontend/src/utils/instance_utils.js, shared/annotation.py
1) Fix global attribute label file permission https://github.com/diffgram/diffgram/commit/05b7d1f09dfb1d3318c4f2f6ff049e6f71f29cd7
2) Fix undefined https://github.com/diffgram/diffgram/commit/37b756379b683e8bf5abb886543d4b66592b0f64
3) Fix bug with Scripts expansion panel https://github.com/diffgram/diffgram/commit/fef0fdf12697170dfa9e5fe8618c0c210abe2686
rest of commits starting with -> 
https://github.com/diffgram/diffgram/commit/35c8e8b614c1e05fccd955e9d6ee0f8e9d745117
To recap highlights of that:
1) Make issues according viewable by default. Before had to create an issue to see the existing issues (in this context).
2) Add a "new issue" button. This means a user does not have to know to right click on canvas. Also makes this accessible to other media types more easily
3) Add a "no …
=> Make Issues Concept more Visible & Fix global attribute label file permission

.github/workflows/diffgram_testing.yaml, default/tests/conftest.py, shared/settings/settings.py, walrus/tests/conftest.py
Changing this URL to be separate for system's url to prevent errors of wrongly running tests on an in-user diffgram DB
=> fix: add unit testing DB url

.github/workflows/diffgram_testing.yaml, frontend/src/components/input/new_or_update_upload_screen.vue, shared/tests/test_utils/data_mocking.py, walrus/methods/input/process_media.py, walrus/tests/methods/input/test_process_media.py
This PR will close #240  I think.
.bmp, .tif and .tiff files will be supported. Original file will go to raw files and a PNG with compress_level=4 is generated because it feels like a good tradeoff between the required processing power and the space saved. Feel free to adjust this as needed. 
Because thumbnail would be generated with the native file extension this approach didn't work. All thumbnails will be generated as JPG with quality=95.
If a new extension gets requested it can be added to the same list as .bmp, .tif and .tiff as long as imageio can read and write it the same way as the other extensions.
@PJEstrada I changed the thumbnail extension to JPG because it is a thumbnail and you don't really see the difference with PNG. It is slightly smaller and blazing fast. It is in a …
=> Add support for BMP, TIF and TIFF files

default/methods/configs/is_open_source.py, default/routes_init.py, frontend/src/components/main_menu/menu.vue, frontend/src/components/main_menu/menu_marketing.vue, frontend/src/components/marketing/home_unbounce.vue, frontend/src/components/regular/ahref_seo_optimal.vue, frontend/src/components/user/account/user_data_platform_new.vue, frontend/src/components/user/login.vue, frontend/src/services/configService.js
When visting "/" route now when the installation is not open source we will redirect to landing page,
If the installation is open source we redirect to login page or dashboard
Also removed the old marketing toolbar buttons and changed some of the menu buttons to go to the landing pages instead of marketing components.
I still haven't deleted the components, but if you think now is the time to remove them I can do it in this PR too.
=> Remove old marketing toolbar and update redirects to landing page

frontend/cypress/integration/diffgram/export_annotated_data/export_spec.js, frontend/cypress/integration/diffgram/task_template/02_task_submit_to_review_spec.js, frontend/cypress/support/commands.js, frontend/src/components/export/export_home.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, walrus/methods/data_mocking/generate_data.py
After moving and occluding instances the UI got to a state where the instance was being dragged only by hovering it. The reason was a return statement that was not allowing the drag flag to be resetted
=> Fix instance being dragged without clicking bug

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/toolbar.vue, frontend/src/store.js
1) Add reminder: `Add new events individually in toolbar, e.g. @change="$emit('update_something').`   because I added a `prior_settings` comparison before recalling that pattern
2) Improve update_user_settings_from_store() to grab all values. I removed some old dead values. A small step towards a more universal settings saving
3) trick was that `update_smooth_canvas` needs to in the update after the canvas context loads. otherwise it gets squished by image change it appears.
This way the setting saves in veux and is retained on reload.
=> Add: Smooth Canvas toggle

frontend/cypress/integration/diffgram/task/task/task_list_user_assign_spec.js, frontend/src/components/instance_templates/instance_template_creation_dialog.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts
Target reticle was disappearing when deleting a node while drawing a relation. This behaviour is now fixed.
=> fix: target reticle display on template creation

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/vue_canvas/current_instance_template.vue, frontend/src/components/vue_canvas/instance_list.vue, frontend/src/components/vue_canvas/instances/KeypointInstance.ts, frontend/src/utils/instance_utils.js, frontend/tests/unit/annotation/annotation_core.spec.js
Now we can draw and edit the keypoints instances rescaling based on fixed point.
Logic is as follow:
-  We scale fixing the point on the opposite direction of the control point.
- Example: we rescale on the right control point => the left control point stays fixed.
- We rescale the top right point => the bottom left point is fixed.
=> Rescale Keypoints Snapping to Corners

local_dispatcher/requirements.txt
Upgrade to new flask version and set correct version for `markupsafe` package.
=> Upgrade dispatcher dependencies

default/methods/account/billing/billing_stripe_new.py, default/methods/user/account/account_new.py, frontend/src/components/account/billing/credit_card.vue, frontend/src/components/account/billing/order_premium.vue
This can happen if a new user gets invited to a project, or if a user tries to upgrade and has no accounts yet.
We are adding a fallback method to the credit card payment so that if the user does not provide an account, it will use the first one on the account list and if it does not have any accounts. It will create a new billing account for the user.
This a bug on the order_premium component where the account_info component was not getting properly imported and thus, it was not fetching the account data.
=> fix: Fix billing issue for users with no accounts.

frontend/src/components/project/settings.vue, frontend/src/components/share/share_member_list.vue, frontend/src/components/share/share_new_member.vue
[Add: View existing members from Share concept](https://github.com/diffgram/diffgram/commit/0157046fbd0ee59cc9afb40299d683d53ea9d3ec)
-> Add dialog to show existing users when inviting
-> Add extra button to jump back to user mode when in API creation (design intuition wise the button is in same place so the user doesn't have to think about the selector, otherwise if they view existing first then it feels confusing)
-> Upgrade and clean other buttons
-> Add flag to optionally not show the "existing users" e.g. on settings page
-> Clean username / move client ID to otherwise empty step
Thinking design perspective here, member_id maybe useful for debugging but not average user
-> Remove titles so parent component can set relevant title, or can completely remove it in cases where it's …
=> Tiny fix settings

frontend/src/components/label/label_select_annotation.vue
Now we can search for the labels on all the annotation UI's using the `label_select_annotation` component.
- Text UI
- Image/Video
- 3D interface
=> DAD-174 Add search on labels selector

frontend/src/router/router.js
When we manually set props like this then it appears we need to also set default props. becuase it was not receiving a project string id the automatic project changer could not work
closes #799
=> Fix: Missing param

frontend/cypress/integration/diffgram/user/user_login_spec.js, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/labels_view.vue, frontend/src/components/main_menu/menu_project.vue, frontend/src/components/main_menu/menu_tasks.vue, frontend/src/components/report/report.vue, frontend/src/store.js, shared/settings/settings.py
[Add dedicated change project button for rare contexts](https://github.com/diffgram/diffgram/commit/abc75715b9ac800c23bfd29c9b1aa06cb0432668) 
Keeping in mind the context that we normally set the project when the user logins in, in the rare event that there is no project:
1) The part that was confusing was that change project was within the project menu.
This meant that various conditions that made sense for most of the menu did not make sense for change project.
2) Now there is a dedicated change project, that will only show up when there is no active project, the user's email is verified, and there is a project available
3) Now the project and task menus only shows when there's an active project.
While there's some UI trade offs for now that seems simpler then the disabled
while we …
=> Login new assumptions

frontend/src/components/source_control/file_preview.vue, frontend/src/components/task/task/task_list.vue, frontend/src/components/vue_canvas/video_drawable_canvas.vue
Since requests get cancelled on the on_destroy method of the video preview canvas, we need to await next tick before doing the task list request, otherwise the task list request will also get cancelled.
=> Fix Task List Fetching

walrus/methods/export/export_web.py
Use the user creating the request instead of the project's main member.
=> Fix Export Generation Limit Checks

default/methods/user/logout.py, docker-compose.yaml, eventhandlers/main.py, eventhandlers/startup/system_startup_checker.py, shared/auth/KeycloakDiffgramClient.py, shared/permissions/KeycloakPolicyEnforcer.py, shared/settings/settings.py, walrus/methods/startup/system_startup_checker.py
- Adds automatic creation of key cloak realm and client.
- Creates client roles based on existing diffgram roles. For now there is no integration between these roles.
- Adds startup checks when Keycloak is enabled.
=> Add Basic Roles Creation for Keycloak Setup

shared/data_tools_core_s3.py, walrus/methods/input/process_media.py
New S3V4 Signatures seem to only allow 7 days max as regeneration time for signed urls.
=> Fix Expiration TImes For S3 Client Defaults

default/methods/auth/oidc/oidc_auth_callback.py, default/methods/user/login.py, default/methods/user/logout.py, frontend/src/components/user/login.vue, shared/helpers/permissions.py
* Optimizes token storage size to be less than 4Kb in  order to keep using client side cookies. As a sidenote, if we ever want to move away from client side cookies we might need to think about server side storage of the session (on DB, redis, memcached or filesystem) or  localstorage storage of the session (not as safe as cookies)
* Change the logout flow to now have a button in login screen instead of directly login with SSO provider.
=> Cognito Token Storage Size & Login Optimizations

frontend/src/components/attribute/attribute_group_wizard.vue
Archiving tree view nodes was not working due to an incorrect filtering of the ids.
This PR fixes the issue.
=> Fix Archiving Tree View Items

default/methods/tag/tag.py, frontend/src/components/source_control/directory_list.vue, frontend/src/components/tag/tag_display_and_select.vue, frontend/src/components/tag/tag_select.vue, frontend/src/components/task/job/job_list.vue, shared/database/tag/tag.py
(I have been merging into AI-3-support branch already so just using this more to highlight overall changes, issues, open questions etc)
1) Adds tag concept to datasets
2) Adds UI control (add/remove) of tags
3) Various helper and generics for dealing with tags
4) Adds ability to remove applied tags
5) Adds visual of tags on various places for datasets
most likely all can be v2
[]unexpected behavior: if the tag exists, and the user uses the search and hits enter it (instead of selecting it), then it fails
feels like something with vuetify combobox
(Does not apply to new tag creation, or normal selection)
[]thoughts on deleting or editing tag names in general (not in Apply case which is already covered, but like global admin of tags)
[]should you be able to inherit tags from a dataset?
e.g. …
=> Improve tags

frontend/tests/unit/stats/stats_panel.spec.js
Since @anthony-sarkis moved stats tab, there where 2 units to hide/show visibility of that tab. They didn't have sense anymore, so I just deleted those 2
=> Remove outdated unit tests for the stats

shared/database/source_control/file.py
Since blob path is at the asset level too, it makes sense to include it so signed urls can be built with those values outside of diffgram.
=> fix: add bucket to serialized assets 

default/methods/project/view_project.py, default/methods/source_control/working_dir/directory_update.py, default/methods/source_control/working_dir/new_directory.py, frontend/src/components/user/home/annotator_dashboard.vue, frontend/src/components/user/home/dashboard.vue, shared/alembic/versions_opencore/alembic_2022_10_13_06_51_61977555605b_new_indexes_for_dirs_and_events.py, shared/database/project.py, shared/database/source_control/working_dir.py
* Remove project serialization on endpoints to avoid rendering a full list of dirs.
* Limited the number of dirs to be added to project's cache
Eventually I think the best way to go is to completely remove the cache of dirs in project. The only reason for it's existence is for having a dir to get when changing projects. But the correct way should be to have a paginated dir list and then go to the first dir on that paginated list. That way the backend will not serialize huge jsons when there are 3K dirs on a project.
Other thing that was removed is the user visit history component. The query is now extremely slow due to the event table having no indexes. We cannot add indexes to this table since it is very write intensive. For now I'll remove it until we have the time to define a better …
=> fix: performance fixes for projects with large dirs list

default/methods/source_control/file/file_get_signed_url.py, frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/media_core.vue, frontend/src/components/source_control/file_manager_sheet.vue, frontend/src/services/fileServices.ts, shared/database/audio/audio_file.py, shared/database/image.py, shared/database/source_control/file.py, shared/database/text_file.py, shared/url_generation.py
* Removes duplicate calls to instance list fetch for images in general.
* Removes calls to get signed url on file list when being on task context.
* Avoid thumbnail generation on first fetch if file is first opened in task context.
I have...
I have...
=> Fix: Optimize Signed URL Fetch on task context

frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/attribute/global_attributes_list.vue
Leaves the first global attribute opened by default when opening a file that has at least 1 global attributes on its schema.
I have...
I have...
=> AI-35: feat: open first global attribute panel by default

shared/helpers/sessionMaker.py
Context of extra guard for unexpected / unoptimized queries
This will now throw error for unexpectedly long queries
There's a lot more we can do around this and making specifics a setting etc but just wanted to get this V1 live to prevent bad things
...
I have...
I have...
=> perf: Add statement_timeout

frontend/cypress/e2e/diffgram/annotate_files/08_video_annotation_tools.cy.js, frontend/src/components/annotation/media_core.vue
Avoids thumbnail creation once generated.
I have...
I have...
=> Fix: Avoid creating thumbnails Once generated

default/tests/shared/query_engine/expressions/test_dataset.py, frontend/src/components/source_control/file_preview.vue, shared/alembic/env.py, shared/alembic/versions_opencore/alembic_2022_11_25_10_07_4748c936ca87_index_dataset_explorer.py, shared/query_engine/expressions/dataset.py, shared/query_engine/expressions/expressions.py, shared/query_engine/sqlalchemy_query_exectutor.py
The reason dataset explorer queries where now slower was due to the new condition `file.parent_id IS NOT NULL`. It seems that 'normal' indexes tend to ignore nullable columns, so you have to go with either adding an order statement to the index, or a partial index (this PR).
Now the slow query takes about 3-4 seconds to respond
I have...
I have...
=> fix: Add Partial Indexes to nullable parent ID column

frontend/src/components/annotation/annotation_core.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/helpers/InstanceStore.ts
With the current architecture, every annotation interface keeps its own state and all the implementation of all the functionality. This was working fine a year ago, when Diffgram had only one annotation interface (Image + Video). Since then, we are growing rapidly, and now we have 5 (Image + Video, 3D, Text, Audio, Geo) different annotation interfaces, and potentially have more in the future, which will lead to more repeated code
Another reason, is a Compound File interface that are WIP right now. The problem here is that we should be able to annotate 2 different files simultaneously, with possibility to have same toolbar and same sidebar (and current architecture isn't ideal for this)
**InstanceStore** class is an management class that will store instances in an object with the key of …
=> Instance Store

default/methods/report/report_runner.py, frontend/src/components/report/CSVReportFormatter.ts, frontend/src/components/report/report.vue
1) Enables second group by label
2) Enable CSV download for second group by label
3) Fix No result cases to show no results instead of JSON error
4) Fix Schema label name for some cases
=> Fix report label names

default/docs/swagger_spec.json, default/main.py, default/methods/attribute/attribute_template_group_update.py, default/methods/source_control/file/file_update_metadata.py, frontend/src/components/attribute/attribute_group.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/attribute/attribute_group_wizard.vue, frontend/src/components/attribute/attribute_select.vue, frontend/src/services/attributesService.ts, frontend/src/types/attributes/AttributeTemplateGroup.ts, shared/alembic/versions_opencore/alembic_2023_02_23_08_38_7c18149a20c8_add_read_only_flag_to_attributes.py, shared/database/attribute/attribute_template_group.py
Adds read only attribute flag to allow uploading attribute values that users don't want to get annotated. Useful for metadata on files.
I have...
I have...
=> feat: add read only attribute

install.py
fix: Install.py user correct URL when S3 is selected for connection tests.
I have...
I have...
=> fix: Install.py user correct URL when S3 is selected for connection tests.

default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue, frontend/src/components/annotation/sidebar_factory.vue, frontend/src/services/instanceServices.js
We need to eventually standarize all these /annotation/list endpoints to be GET methods and not POST. For now, we're doing a check for the existence of a payload.
=> Fix Child List Annotations Bug

frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/toolbar.vue
fix: persist last instance type selection across reloads
I have...
I have...
=> fix: persist last instance type selection across reloads

default/methods/attribute/attribute.py, default/methods/attribute/attribute_template_group_update.py, default/methods/source_control/file/file_browser.py, frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/annotation_ui_factory.vue, frontend/src/components/attribute/attribute.vue, frontend/src/components/attribute/attribute_group_list.vue, frontend/src/components/attribute/attribute_group_wizard.vue, frontend/src/components/attribute/attribute_new_or_update.vue, shared/database/attribute/attribute_template_group.py, shared/utils/source_control/file/file_transfer_core.py, walrus/main.py, walrus/methods/data_mocking/generate_data.py, walrus/methods/input/process_media.py, walrus/methods/input/upload.py
Fixes a variety of issues while ordering attributes.
1) New attributes do not destroy existing order (ordinal defaults to 9999)
2) Attribute option updates (e.g. for Radial) no longer call for a global refresh
improving performance (e.g. local update instead of 100 Attribute groups x 100 options refresh
3) Improved loading and queuing to harden cases of multiple edits while loading confusing ordering
4) Fixes common case for 400 error by making `kind` optional in re-ordering update case
5) Other small cleaning, updating, and logging items
This was mainly in the UI context but also applies to API/SDK for some items e.g. 1) and 4) 
General design notes for future
* Archive still calls for a global refresh
* In general the existing code leans too much on Vue and should be more generic JS/TS …
=> Attribute Ordering Improvements

default/methods/task/task_template/job_launch.py, default/methods/task/task_template/job_new_or_update.py, default/tests/methods/task/task_template/test_job_new_or_update.py, frontend/src/components/task/job/job_edit_pipeline.vue, frontend/src/components/task/job/job_new.vue, frontend/src/components/task/job/task_template_wizard_creation/step_attach_directories_task_template.vue, shared/query_engine/expressions/dataset.py, shared/query_engine/expressions/file.py
Main item is [Fix query expression assumptions for file](https://github.com/diffgram/diffgram/commit/7035f0abc4dac7bfb5e19ee52ada5372fee5cc17)
Also:
[fix str int](https://github.com/diffgram/diffgram/commit/454f5cf3999a7c57d889ecaf94fda0ea65ed142a)
[Remove duplicate condition](https://github.com/diffgram/diffgram/commit/d73ff57ed36ec0ca26e73f11d961164ba6a39ad8)
File query reserved items like `created_time` were appearing to work, but returning erroneous results. e.g. created time set to `file.created_time >= "2023-06-22"` and still returning results `created_time: "2023-06-15T01:02:50.313507"`
Same query on fix:
It was creating this statement which (appears to be) invalid:
```
AND file.id IN (SELECT anon_1.id
FROM (SELECT file_1.id AS id
FROM file AS file_1, file
WHERE …
```
=> Fix jobset output dir

default/methods/source_control/file/file_get_signed_url.py, frontend/src/components/annotation/annotation_area_factory.vue, frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/components/annotation/image_and_video_annotation/media_core.vue, frontend/src/services/fileServices.ts, shared/alembic/versions_opencore/alembic_2023_08_14_14_34_e93e2edbb6b7_add_image_error.py, shared/connection/azure_connector.py, shared/connection/s3_connector.py, shared/data_tools_core_azure.py, shared/database/audio/audio_file.py, shared/database/geospatial/geo_asset.py, shared/database/image.py, shared/database/point_cloud/point_cloud.py, shared/database/source_control/file.py, shared/database/text_file.py, shared/url_generation.py
This pull request improves the UI surface of Custom signed URL errors.
For example in screenshot, purposefully created a "bad" result, and it is showing that result to user. 
This is in context that each user may have permission issues, or the 3rd party signed service may operate in unexpected ways, and we need to distinguish between when that service throws a message vs some other processing errors
Also removes `create_thumbnails` concept.
-> We don't want to store artifacts unless we have to.
-> Given the desire to always render the full canvas if possible, getting a preview in this context doesn't make sense
e.g. it's less of an optimization and more of a blocker to then showing user full exp.
-> In general if we want to do preview objects in the future we need a fresh plan that …
=> Improve custom url error handling

.github/workflows/e2e_tests.yaml
New AWS K8s runner for E2E tests. All relevant changes have been made in the actions-runner-k8s repo on [this PR](https://github.com/diffgram/actions-runners-k8s/pull/1).
=> New runner

frontend/.nginx/nginx.conf
remove as per https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/#ok-but-how-does-this-increase-the-security-of-my-ingress-controller
=> Remove autoindex context of Increasing the security bar in Ingress-NGINX v1.2.0

frontend/src/components/annotation/image_and_video_annotation/annotation_core.vue, frontend/src/utils/hotkey_listener.ts
Fix a bug with hotkeys that happens in compound file context with multiple images. Updated HotkeyListener documentation to make it easier to use.
Bug Description:
Pressing a hotkey makes registered hotkey callbacks fire for all the image annotation panes
=> Fix hotkeys for Multi images (Compound files)

frontend/src/components/source_control/dataset_explorer.vue
Fixes
https://github.com/diffgram/diffgram/issues/1571
- This was a "Cosmetic" only item, since the '0' object was not a valid file there was nothing to unselect.
- The root of it injecting the '0' can be solved as part of refactoring the file push and concat block which should be seperate functions.
Additional Context 
- Error: Cannot create property 'selected' on string '0'
- In theory a file object should never be a string '0', however, it seems to be adding this in, so until that root item is solved adding this check to filter out the '0's (which aren't valid file objects)
- In limited testing it only seems to happen once, so some process is adding it in a funny way
For example:
=> Fix Cosmetic "Dataset Explorer, after scrolling down a certain amount error"

frontend/src/components/annotation/annotation_ui_factory.vue, shared/database/event/event.py
[Add regressed instance ID update](https://github.com/diffgram/diffgram/commit/12e18f95fe825a3b3c14600320684bad8c4ebe80) 
add_ids_to_new_instances_and_delete_old() is needed for Object level Global attributes too.
In local testing this solved the global attribute update context when saving the same global attributes without reloading
Fixes https://github.com/diffgram/diffgram/issues/1594
=> Fix global object attribute updates in some contexts

docker-compose.yaml, install.py
Context of https://github.com/diffgram/diffgram/issues/1615
The backdrop here is:
* Docker compose (local test install option) offers a local or remote db. In the case of remote db being used the health checks appear to be failing.
* `tianon/true` is correct in of itself in theory, however in conjunction with the health check it will fail.
The proposed solution is to make the healthcheck variable. In the remote case it will echo that it's not supported.  That avoids having to have the postgres image loaded etc when remote db is actually being used. that is cleaner and also prevents debug issues or confusions with a db running that's not being used.
Also updated default postgres db for local testing to more modern version POSTGRES_IMAGE=postgres:16
=> make healthcheck variable
